### ISSUE TITLE
Board Maintenance: Create milestones

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1088]
### Depedencies

 #1155 

### Overview
Food Oasis needs to adapt its board to the standard of other projects in Hack for LA. 
Milestones must be created and labelled to the issues to enable prioritisation and pace estimation for the project

### Action Items

- [x] Identified milestone names
- [x] Add milestones on the board
- [ ] Label each prioritized backlog issue to a milestone

### Resources/Instructions
https://docs.google.com/document/d/1OnxFXU-YDAmNA1XwrlQYiOiCSWXG5Mfk2oThmpbh1g0/edit

**Comment by fancyham** [comment]
We are trying this out with an [Embeddable Widget 1.0](https://github.com/hackforla/food-oasis/milestone/8) milestone.

**Comment by staceyrebekahscott** [comment]
As part of the Impact Sprints initiative, I am tasked with revising the milestones. Assigning this to myself as a reminder to either revise this issue or create a new, more current issue.

**Comment by staceyrebekahscott** [comment]
Determined that this issue details work that is being done in #1119. Due to this redundancy, this issue can be closed.
