### ISSUE TITLE
Embeddable widget usability issues / requested features

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1098]
### Overview
Some features we need to support embedding our map onto other websites — often these are neighborhood council websites, city websites, service providers, or food banks and food rescue organizations that supply food pantries and meal programs.

This would allow these websites to embed a live Food Oasis map with current food pantry/meal locations on their webpages while helping Food Oasis us get information to food seekers.  A real win-win.  

To do this, we need to support some new functionality that are particular to embedding on these types of sites:
- Centering map on a particular location (useful for orgs that serve a particular location)
- Extra-narrow widths: Third-party sites will often have a margin around their embeds, so either we

One issue is that while we already support narrow smartphones (iPhone 5), embedding potentially removes pixels horizontally so the UI would need to be even narrower.

A nice to have would be to reduce initial load time or show a ‘loading’ indicator.  Currently, our iFrame displays a white box while javascript libraries are loading (which may be quite large), so improving load time or showing an indicator will make our widget feel more responsive and not broken.

### Action Items
Things we want before releasing:
- [x] (x No longer necessary) Very narrow devices with iFrames in it (iPhone 5 with iFrame inset in margins)
    - [x] x Option 1) Give instructions to use the full width of the screen when embedding our site on narrow screens.
    - [x] x Option 2) Change our layouts to support extra-narrow screens (see example below)
        - [x] √ Fix stacking of buttons on very narrow buttons - perhaps by dropping or truncating text?
        - [x] √ Fix bottom row so it doesn’t get crammed up (#1130)
- [x] #1101 
- [x] Want to specify iFrame map’s default location and filter to center map on a specific location (#1165)
- [x] Logos and text for bottom bar for other regions (Hawaii) (#1130)

<img src=https://user-images.githubusercontent.com/3376957/142556648-2dbdb7d9-5033-4771-9203-ae2d21a3ca18.jpeg height=400> <img src=https://user-images.githubusercontent.com/3376957/142961482-7bd24b64-958e-474e-870e-f0cd4dab30b4.jpeg height=400>

**Comment by fancyham** [comment]
A nice to have would be to reduce initial load time or show a ‘loading’ indicator.  Currently, our iFrame displays a white box while javascript libraries are loading (which may be quite large), so improving load time or showing an indicator will make our widget feel more responsive and not broken.

Added to the checklist above.

**Comment by fancyham** [comment]
Looks like it's working okay now:
- Centering was taken care of in #1165 by showing a neighborhood boundary.  
- The layout problems continue if embedded with large margins on small device, but in the [wiki's embedding instructions](https://github.com/hackforla/food-oasis/wiki/Embedding-Food-Oasis-in-Your-Web-Site) we say use full 100% width which would work on an iPhone 5/SE.  So ensuring responsive usability will be the responsibility of the embedding designers.
- Bottom logo layout looks better — looks like it was fixed in #1130

**Comment by fancyham** [comment]
I think these issues are all taken care of, so closing!
