### ISSUE TITLE
Label and milestone review and audit

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#1119]
### Overview
We need to perform a weekly check on issues to make sure they all conform to our label and milestone schema.

### Action Items
- [ ] Check the following to make sure that they are all 0 open (Links for checking to make sure that all issues either have a ___ or a ____ missing label)
   - [ ] [Role](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+-label%3A%22Role%3A+Business+Analysis+%2F+Product%22+-label%3A%22Role%3A+Back-end%22+-label%3A%22Role%3A+Copywriting%22+-label%3A%22Role%3A+Database%22+-label%3A%22Role%3A+Design+UI%2FUX%22+-label%3A%22Role%3A+Front-end%22+-label%3A%22Role%3A+Product+Management%22+-label%3A%22Role%3A+User+Research%22+-label%3A%22Missing%3A+Role%22)
   - [ ] [size](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+2pt%22+-label%3A%22size%3A+3pt%22+-label%3A%22size%3A+5pt%22+-label%3A%22size%3A+8pt%22+-label%3A%22size%3A+13pt%22+-label%3A%22Missing%3A+Size%222)
   - [ ] [feature](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+-label%3A%22Feature%3A+Accessibility%22+-label%3A%22Feature%3A+Administrative%22+-label%3A%22Feature%3A+Agenda%22+-label%3A%22Feature%3A+Analytics%22+-label%3A%22Feature%3A+Board%2FGithub+Maintenance%22+-label%3A%22Feature%3A+Design+System%22+-label%3A%22Feature%3A+Infrastructure%22+-label%3A%22Feature%3A+Onboarding%22+-label%3A%22Feature%3A+Search%22+-label%3A%22Feature%3A+Testing%22+-label%3A%22Feature%3A+Usability%22+-label%3A%22P-Feature%3A+Admin+Dashboard%22+-label%3A%22P-Feature%3A+Landing+Page%22+-label%3A%22P-Feature%3A+Organization+Form%22+-label%3A%22P-Feature%3A+Organizations%22+-label%3A%22P-Feature%3A+Registration+%2F+Login%22+-label%3A%22P-Feature%3A+Stakeholder+Record%22+-label%3A%22P-Feature%3A+Tenant+Specific+Other%22+-label%3A%22P-Feature%3A+Tenant+Specific+Static+Content%22+-label%3A%22P-Feature%3A+Volunteer+Dashboard%22+-label%3A%22P-Feature%3A+Map%22+-label%3A%22Missing%3A+Feature%22+-label%3A%22P-Feature%3A+Suggestions%22)
   - [ ] [milestone](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone+-label%3A%22Missing%3A+Milestone%22+)
     - [ ] Add any label missing (e.g., a new feature label go added to the project, but didn't yet get added here) and update link 
   - [ ] issues that have not yet been added to [project board](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue+is%3Aopen+no%3Aproject)
     - [ ] add to project board
- [ ] if changes were made, recheck to make sure all links ended up 0/0
- [ ] Audit for issues with Missing labels (to determine if we are making progress)
   - [ ] Copy this audit report format to a comment below
```
Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] role, ending at
   - [ ] milestone, ending at
```
   - [ ] perform audit, adding your numbers to your audit report comment
      - [ ] [Role](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+label%3A%22Missing%3A+Role%22)
      - [ ] [size](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+label%3A%22Missing%3A+Size%22)
      - [ ] [feature](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+label%3A%22Missing%3A+Feature%22)
      - [ ] [milestone](https://github.com/hackforla/food-oasis/issues?q=is%3Aopen+is%3Aissue+no%3Amilestone+label%3A%22Missing%3A+Milestone%22)
      - [ ] Number of issues in the [New Issue Approval column](https://github.com/hackforla/food-oasis/projects/8#column-15251628)
         - [ ] number of issues already assigned to people in the column

**Comment by Benbaillou** [comment]
@entrotech @fancyham @souronion @ryu-jieun @LIlinit - Team, I will work on cleaning the issues and adding correct labels. I shall ask you some information during this task on your issues.

**Comment by Benbaillou** [comment]
Date: 
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] role, ending at
   - [ ] milestone, ending at

**Comment by Benbaillou** [comment]
Date: 12/14/21

 Did you have to update the 0/0 links above? if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
 Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
 size, ending at: 59
 features, ending at: 1 (labeled "New feature")
 role, ending at: 0
 milestone, ending at: 93
I added a project that was missing from the board as well as feature and milestone missing.

**Comment by ExperimentsInHonesty** [comment]
Number of issues in the New Issue Approval column: 34
 number of issues assigned to people in the New Issue Approval column: 8

**Comment by Benbaillou** [comment]
Date: 01/04/21

**Status**
size, ending at: 58
features, ending at: 1 (labeled "New feature")
role, ending at: 0
milestone, ending at: 92

**Comment by ExperimentsInHonesty** [comment]
Number of issues in the New Issue Approval column: 34
number of issues assigned to people in the New Issue Approval column: 7

**Comment by Benbaillou** [comment]
### Date: 01/11/22

Did you have to update the 0/0 links above?

- [ ] No - everything was at 0/0
- [ ] yes
Done: _N/A_

**Status**

- size, ending at: 55 => Done: issues closed or sized
- features, ending at: 1 (labeled "New feature")
- role, ending at: 0
- milestone, ending at: 96 => Done: 4 new issues added

- Number of issues in the New Issue Approval column: 31
- Number of issues assigned to people in the New Issue Approval column:  3 ( To check if 1 assignee is still an active engineer part of the team => question asked to John)

**Note:**
Size:
1) Gigi and Ben to meet 01/15 to have a first sizing overview
2) John, Bryan Gigi and Ben to meet to size and clean the board w/c 17 Jan
Milestone:
Roadmap under validation => milestones to be created and labelled by Feb 2022

**Comment by Benbaillou** [comment]
Date: 01/18/22
Did you have to update the 0/0 links above?

- [ ] No - everything was at 0/0
- [ ] yes


size, ending at: 53 => Done: issues closed or sized

features, ending at: 1 (labeled "New feature")

role, ending at: 0

milestone, ending at: 97 => Done: 3 new issues added

Number of issues in the New Issue Approval column: 31

Number of issues assigned to people in the New Issue Approval column: 3 

Note
Sizing: John, Bryan Gigi and Ben to meet to size and clean the board w/c 17 Jan

**Comment by Benbaillou** [comment]
### Date:  01/25 /22
- [x] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [x] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [x] size, ending at **27** (vs 27 last week)
   - [x] features, ending at **0** (vs 0 last week)
   - [x] role, ending at **0** (vs 0 last week)
   - [x] milestone, ending at **97** (vs 97 last week)

**Comment by Benbaillou** [comment]
## Date: 01/25 /22

- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at 27 (vs 27 last week
   - [ ] features, ending at 0 (vs 0 last week)
   - [ ] role, ending at 0 (vs 0 last week)
   - [ ] milestone, ending at 97 (vs 97 last week)

**Comment by staceyrebekahscott** [comment]
@itserindean FYI, moved this to In Progress and added myself, Rylan and Yi Min as assignees. Note that I have also assigned myself to issue #1088 as per my conversation with Bonnie asking me to review and revise the milestones to include Impact Sprint goals.

**Comment by staceyrebekahscott** [comment]
Started spreadsheet to reevaluate labels and milestones: [Labels and Milestones Revised Aug 2022](https://docs.google.com/spreadsheets/d/1CHMUTNB_Y7R--nQ3AGYuRvfbm4nHWr8hDXQ2Xt6QGT4/edit#gid=999295171)

Label review is necessary because there are too many labels to be useful. Reducing # of labels and clarifying their usage will make them more effective, and improve issue workflow. 
- not being used at all
- too specific to be frequently used
- vague/ no description for usage
- redundant with a process or another similar label

Milestone review is necessary because the ones in Github are outdated. There are several docs for Milestones and Roadmaps but it does not appear as if any one of them is current. Need to establish Roadmap and Milestones to match current project objectives, which also need to be clearly identified. 

- [ ] Review labels with the group and confirm understanding of usage 
- [ ] If procedure replaces a label, confirm understanding of procedure and/ or detail procedure in column heading
- [ ] Review roadmap/ milestone docs and determine if any are still current
- [ ] Build new roadmap/ milestones and review with the team to get consensus
- [ ] Update milestones in Github

**Comment by staceyrebekahscott** [comment]
Selected milestones for all issues in In Progress and most in Prioritized Backlog. The ones not properly marked are Dev and I am not sure how they will fit into the new milestones. And the current milestones are subject to change, but they are the matched to the most relevant of the current milestones in Github.

**Comment by staceyrebekahscott** [comment]
Selected milestones for issues in Prioritized Backlog, Waiting and Icebox. Any issues with the Missing: Milestone label does not fit into any current milestone. Started updating Missing: Size labels.

**Comment by staceyrebekahscott** [comment]
Closed Milestone: [Embeddable Widget 1.0](https://github.com/hackforla/food-oasis/milestone/8): No open issues, All issues closed.

**Comment by staceyrebekahscott** [comment]
Added New Milestone: [Process Improvements- Impact Sprints 2022](https://github.com/hackforla/food-oasis/milestone/20)
Added New Milestone: [Volunteer Engagement- Impact Sprints 2022](https://github.com/hackforla/food-oasis/milestone/19)
Added New Milestone: [Partnership Engagement- Impact Sprints 2022](https://github.com/hackforla/food-oasis/milestone/18)

Closing this issue as completed, as a new process to address label and milestone review will be developed via issue #1323.

**Comment by sumit-sharma92** [comment]
Date: 2024-09-25
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] role, ending at
   - [ ] milestone, ending at

**Comment by farahrobleh** [comment]
Date: 2024-19-11
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet). 
   - Yes, add a feature
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] role, ending at
   - [ ] milestone, ending at
   - [ ] Number of issues in the new issue approval column
   - [ ] Number of issues in the icebox with no dependency

**Comment by ExperimentsInHonesty** [comment]
Date: 2025-02-26
- [x] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
   - Had to update the features
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at 95/483
   - [ ] features, ending at 14/494
   - [ ] role, ending at 11/330
   - [ ] milestone, ending at 23/577
   - [ ] Number of issues in the new issue approval column 109
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by TifNi** [comment]
Date: 2025-04-16
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
   - We added and removed features.
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] role, ending at
   - [ ] milestone, ending at
   - [ ] Number of issues in the new issue approval column
   - [ ] Number of issues in the icebox with no dependency

**Comment by ExperimentsInHonesty** [comment]
Date: 2025-04-22
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet). 
   - adding a few labels to issues
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at 94/494
   - [ ] features, ending at 14/534
   - [ ] role, ending at 10/331
   - [ ] milestone, ending at
   - [ ] Number of issues in the new issue approval column 100
   - [ ] Number of issues in the icebox with no dependency 0

**Comment by ExperimentsInHonesty** [comment]
Date: 2025-04-30
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
   - Added interface link
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] size, ending at
   - [ ] features, ending at
   - [ ] role, ending at
   - [ ] milestone, ending at
   - [ ] Number of issues in the new issue approval column
   - [ ] Number of issues in the icebox with no dependency

**Comment by TifNi** [comment]
Date: 05-14-2025
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
   - No
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at: 11/331
   - [ ] size, ending at: 100/494
   - [ ] features, ending at: 17/534
   - [ ] Interface, ending at: 0/0
   - [ ] milestone, ending at: 20/585
   - [ ] Number of issues in the new issue approval column: 115
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by wmao8** [comment]
Date: 05-20-2025
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
   - No
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at: 10/331
   - [ ] size, ending at: 100/494
   - [ ] features, ending at: 15/534
   - [ ] Interface, ending at: 0/0
   - [ ] milestone, ending at: 12/581
   - [ ] Number of issues in the new issue approval column: 115
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by TifNi** [comment]
Date: 2025-05-21
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
   - Added labels to issues
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at: 11/331
   - [ ] size, ending at: 102/494
   - [ ] features, ending at: 17/534
   - [ ] Interface, ending at: 3/0
   - [ ] milestone, ending at: 15/581
   - [ ] Number of issues in the new issue approval column: 116
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by TifNi** [comment]
Date: 2025-06-03
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at: 13/331
   - [ ] size, ending at: 101/497
   - [ ] features, ending at: 15/534
   - [ ] Interface, ending at: 1/0
   - [ ] milestone, ending at: 12/582
   - [ ] Number of issues in the new issue approval column: 117
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by ExperimentsInHonesty** [comment]
There are issues that have milestones and the milestone missing label, please review https://github.com/hackforla/food-oasis/issues?q=is%3Aissue%20label%3A%22Missing%3A%20Milestone%22%20milestone%3A*

**Comment by TifNi** [comment]
Date: 2025-08-12
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
   - [ ] Added missing labels
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at: 16/331
   - [ ] size, ending at: 91/508
   - [ ] features, ending at: 16/537
   - [ ] Interface, ending at: 12/4
   - [ ] Complexity, ending at: 172/1084
   - [ ] milestone, ending at: 12/585
   - [ ] Number of issues in the new issue approval column: 106
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by TifNi** [comment]
Date: 2025-09-09
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at: 10/332
   - [ ] size, ending at: 85/515
   - [ ] features, ending at: 11/538
   - [ ] Interface, ending at: 9/4
   - [ ] Complexity, ending at: 156/1093
   - [ ] milestone, ending at: 13/586
   - [ ] Priority, ending at: 54/0
   - [ ] Number of issues in the new issue approval column: 107
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by TifNi** [comment]
Date: 2025-10-21
- [ ] Did you have to update the 0/0 links above?  if yes, please say what you did (e.g, Added features to the features check above or added an issue to the project board that has not been added yet).
- [ ] Report what the numbers are on issues that are missing labels (e.g., size, ending at 12/5)
   - [ ] role, ending at: 8/332
   - [ ] size, ending at: 83/519
   - [ ] features, ending at: 13/538
   - [ ] Interface, ending at: 9/4
   - [ ] Complexity, ending at: 153/1097
   - [ ] milestone, ending at: 13/586
   - [ ] Priority, ending at: 31/0
   - [ ] Number of issues in the new issue approval column: 107
   - [ ] Number of issues in the icebox with no dependency: 0

**Comment by ExperimentsInHonesty** [comment]
I updated the labels from
size: 1pt = The lift to complete this user story 1-2 hrs
size: 2pt = The lift to complete this user story 3- 4 hrs
size: 3pt = The lift to complete this user story 4-8hrs
size: 5pt = The lift to complete this user story 8-16hrs
size: 8pt = The lift to complete this user story 16-24hrs
size: 13pt= The lift to complete this user story 24+hrs


| label        | Description                             |
| ------------ | --------------------------------------- |
| size: 0.25pt | Can be done in 1.5 hours or less        |
| size: 0.5pt  | Can be done in 2-3 hours or less        |
| size: 1pt    | Can be done in 4-6 hours                |
| size: 2pt    | Can be done in 7-12 hours               |
| size: 3pt    | Can be done in 13-18 hours              |
| size: 5pt    | Can be done in 19-30 hours              |
| size: 8pt    | Can be done in 31-48 hours              |
| size: 13+pt  | Must be broken down into smaller issues |
