### ISSUE TITLE
Update FOLA roadmap

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1125]
### Dependencies

#1155 

### Overview
We need to land a final roadmap to prioritize the work to be done and  to potentially recruit new members based on our identified needs
### Action Items
- [x] Draft the roadmap
- [ ] Set up a team meeting with Eng and Design Leads to revise and approve the final roadmap (PM + Eng + Designers)
- [ ] Finalise the roadmap
- [ ] Link roadmap goals to milestones
- [ ] Set up a revision cadence of the roadmap, eg: every 3 months

### Resources/Instructions
[Draft under revision](https://docs.google.com/document/d/1OnxFXU-YDAmNA1XwrlQYiOiCSWXG5Mfk2oThmpbh1g0/edit#)

**Comment by Benbaillou** [comment]
@gigicobos @entrotech @fancyham - Folks, is it possible to set a quick meeting next week (w/c 29 Nov) to revise the draft on the roadmap we have been working on Gigi an I?

**Comment by fancyham** [comment]
@Benbaillou Sure - send out a scheduling thingy

**Comment by Benbaillou** [comment]
When are you available Thursday 12/2 between 8 am to 12 am Pacific time?

**Comment by fancyham** [comment]
@Benbaillou My schedule is complicated — can you email a scheduling coordination thing like https://xoyondo.com/ or post it on slack for the invitees?

**Comment by Benbaillou** [comment]
Hi. I finalised the draft of the roadmap and edited it in a digest format. Inside the documents I added the goals of the roadmap and a guide to read it.

**Would it possible for you guys to** 
1) Have a read through the[ roadmap draft](https://docs.google.com/document/d/1OnxFXU-YDAmNA1XwrlQYiOiCSWXG5Mfk2oThmpbh1g0/edit#)
2) add your potential comments on the Google document

Let's set up **Monday 12/13** as a first feedback round.

**Comment by Benbaillou** [comment]
duplicate of

**Comment by staceyrebekahscott** [comment]
Upon reviewing the several documents in Drive for the Roadmap, this will need to be evaluated as a PM team. Will work to get a regular weekly meeting for the PMs scheduled.

**Comment by staceyrebekahscott** [comment]
Closing this issue as Stale. The issue of creating a new roadmap and milestones will be addressed by issue #1323.
