### ISSUE TITLE
Redesign the Corrections and Suggested New Listings Administration board and modals

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1131]
### Overview
We want to add some much-needed features to the dashboard of Corrections and Suggested new listings.  

- We get Corrections to organizations from the public via a web form
- We get Suggested New Listings from the public via a different web form

This admin dashboard shows the status of these corrections and suggestions, but right now it's very bare-bones.   These changes aim to make it more useful and usable for admins, has links to make updates.

####Details
Currently, user corrections and new org submissions aren't being processed because they are not visible to admins or volunteers.

We need a way for admins and volunteers to review, triage, track, and view suggestions submitted by the public.  This will allow volunteers to update organization details.  

This is a first step towards supporting more crowdsourced organization submissions and updates.

Issue created as a continuation of issue #1069 to improve the layout of the Suggestions Administration board.

**Current issues:**
  - The current "Suggestions" page does not show the source of the "suggestion". The "Suggestions" will come from three places: "Suggest New Listing", "Send Correction", "Organization Email Reminder".
  - The admin volunteer does not know when the correction/listing/update was submitted.
  - Admin volunteer does not get notified of new suggestions. (separate GitHub issue tbc Gigi C)
  - Suggestions are not recorded in the Organizationedit form. (separate GitHub issue tbc Gigi C)
 
**Proposed Changes:**
Admin Board:

- √ Add columns Submission Date, Type, and Suggestion ID# on the Suggestions admin board.
- √ Add an option to filter by “Type” of suggestion.
- √ Change the status wording from “Closed” to “Accepted”
- Add a "Create New Listing" button so if a suggested new listing is accepted, the admin could create a new listing with the matching fields from the suggestion filled in. The admin could then finish the listing or assign it to a volunteer to verify.

Correction Modal: 
- Change field order to show first information about the suggestion and then tipster details.
- Add fields: Suggestion ID#, Type, Submission Date.
- Add a new button “View Organization” that will open a new tab with the Organizationedit page related to that organization.
- Move buttons to the top right corner of the modal.

Create Listing Modal:
- Change fields showing up on modal to match the fields of the “Suggest New Listing Form”.
- Add fields: Suggestion ID#, Type, Submission Date.
- Added a new button “Create New Listing” that will open a new tab with the Organizationedit page for a new organization with pre-filled data available from the “New Listing” form.
- Move buttons to the top right corner of the modal.

### Action Items

- [x] Create a design for the Suggestions Administration board to include the type of suggestion and date.
- [x] Create design for Correction and New Listing modal.
- [ ] Create a notification email for new suggestions.

### Resources/Instructions

Designs: 
- Suggestions Admin Board: https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=13309-39192&t=10kYMh2I5T5fApVl-4

Designs: https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=6426%3A11578

~~[P1: Suggestions board - 12/02/21](https://drive.google.com/file/d/1j8V5ktyzw1C1QH6zDWlGOchmaJtW-St3/view?usp=sharing)~~
~~[P2: Suggestions Administration Board V2 - 01/15/22](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/Suggestions-Admin?node-id=592%3A104)~~

### Related Issues
#996 --> Logs from "Organization Email Reminder" will be visualized on the "Suggestions" page.
#1139 --> Logs from "Suggestions" accepted logs for each organization will be visualized on the "Status Change" page.

**Comment by gigicobos** [comment]
Hi @entrotech @Benbaillou @fancyham,

Here is the link to the changes for the Suggestions admin board:

[P2: Suggestions Administration Board V2 - 01/15/22](https://www.figma.com/file/9hPmNSsyaH2VMGNz5mffmI/Suggestions-Admin?node-id=592%3A104)

Please let me know if there are any questions.

Thank you!

**Comment by fancyham** [comment]
Thanks — added two comments re: the titling of the Suggestion record details and placement of the organization name.

Perhaps consider in the top right corner, rather than the org name, putting something about the suggestion record up there in addition to or as the primary identifier?
“Suggested correction #102929” (org name would be further down page)
“Suggestion #102929 - Correction (New)”
“Suggested correction for MountainView ADHC”
“MountainView ADHC : Suggested correction #102929”

“Suggested new listing #191219”
“Suggestion $102929 - Add listing (New)”
“Suggested new listing for MountainView ADHC”

**Comment by sei1122** [comment]
Before designing this issue, I’d like to clarify things below.

Figma file:
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=4982%3A9019

### Source of the data
The "Suggestions" will come from three places: 
1. Suggest New Listing ✅ 
2. Send Correction ✅
3. Organization Email Reminder -> where can we find it?

<img width="1317" alt="Screen Shot 2022-05-31 at 9 03 48 PM" src="https://user-images.githubusercontent.com/19811032/171325189-e5a02b10-06b2-4883-9645-30cccffe4598.png">



### Suggestions Administration
<img width="1005" alt="Screen Shot 2022-05-31 at 9 05 45 PM" src="https://user-images.githubusercontent.com/19811032/171325388-8f8535d4-28ac-4bac-a044-bc671c3aaa95.png">

What is each status meaning?
New 
Pending 
Rejected
Closed - > (This is suggested to change to Accepted)

Questions:
- Does the admin volunteer change the status when validating the info? 
- ID (Ticket #) is assigned when the suggestion is created? 

Note: Change the Suggestion Administration title to be more descriptive?

### New listing model

Is this brand new feature? 
<img width="729" alt="Screen Shot 2022-05-31 at 9 11 51 PM" src="https://user-images.githubusercontent.com/19811032/171326010-1ede55fa-50dd-4c93-98f7-41367998330f.png">



### Other questions

- Is each data source validated in a different way?  
    - Suggest New Listing 
    - Send Correction
    - Organization Email Reminder
- Is this feature currently used by admin volunteers. If it is not used, would they use the feature if it was redesigned?  -> because the goal is for this data to be reflected on the website. 
- What are good metrics to measure this redesign?

**Comment by fancyham** [comment]
Good questions!  I’ll do my best to answer based on my understanding:

For item 3 above, we haven’t built the **Organization Email Reminder**, but the Milestone for that project is https://github.com/hackforla/food-oasis/milestone/15 and https://github.com/hackforla/food-oasis/issues/996 which has a design-in-progress PDF mockup.

I believe @entrotech has more detail on **“Status”** but my understanding is that these are way of tracking suggestions:
**New** = a suggestion that hasn’t been acted on yet
**Pending** = Something that is in progress (perhaps being researched) but is not approved yet? 
**Rejected** = Rejected (I think this can be hidden by default)
**Closed** = Probably should be “Accepted” — the idea is that the suggestion was accepted and the listing updated.

I’d add that **another flag for the future** might be “Submitted by organization” — for when we send out emails to orgs asking them to verify or update their listing.  If we want to review those updates, this flag would be helpful to know which suggestions are high-quality and need less verification work.

**“New listing model”**
I think this would be a brand-new feature?    I like how the fields show the suggestions on each line though I wonder if hours can be entered this way?  

This begs the question: how will someone review and update the organizations from the suggestions list?  Would it be two windows side-by-side?  Or would the suggestions be shown on the existing editor screens?  Or some other option?

> Is each data source validated in a different way?
> - Suggest New Listing
> - Send Correction
> - Organization Email Reminder

Sorry, I don’t know this but I imagine it’s different, with the second two being similar to each other.

Suggesting a New Listing : would be nice to copy the fields over to a new draft listing, and perhaps to expose the correct fields on the suggestion form to make that easier — less copy and pasting and retyping.

BUT how often do new listings get created?  Probably not that often!  So maybe lower priority than making corrections easy?



> Is this feature currently used by admin volunteers? If it is not used, would they use the feature if it was redesigned? -> because the goal is for this data to be reflected on the website.

I think submitted suggestions are currently ignored! @entrotech ?

> What are good metrics to measure this redesign?

I’d say ease of use and how quickly someone can review and update listings

**Comment by sei1122** [comment]
@fancyham, @entrotech 

I created a user flow to see the overall steps. 
Currently, we don’t have a way to check whether the info comes from a trusted source or not.
All the information must be verified before the information goes on the website. 

Figma file
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5414%3A9263


<img width="1005" alt="Screen Shot 2022-06-09 at 10 20 07 AM" src="https://user-images.githubusercontent.com/19811032/172906879-a485905f-6599-4498-b07b-8274180a12bd.png">

**Comment by sei1122** [comment]
The current design, both Correction info and Suggests a New listing data go to the Suggestions Admin Board. 
At the last meeting, we found out the admin user needs to back and forth between pages.

To improve this, we pivoted direction. 
1. Correction info ----> Verification dashboard column
2. Suggest a New Listing ----> Suggestions Admin Board 


Here is the new user flow for the 1 and 2
<img width="595" alt="Screen Shot 2022-06-14 at 5 06 07 PM" src="https://user-images.githubusercontent.com/19811032/173711526-ad580abe-86ff-4249-9e95-a1ae8369e72e.png">


Figma files
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5524%3A9295
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5529%3A9662

**Comment by fancyham** [comment]
Looks really good!  

On the “Suggest a new listing”
- You might already be on the same page but we might be able to save some copying and pasting if we:
  - Have a button for each new org suggestion (column 2) that creates a draft org record and copies over the simple fields like “organization name” and similar matching text fields automatically.  
  - More complex fields like “hours” could be displayed at the top of that draft org similar to a suggestion. 

![#1131 Sketch for creating new org from suggestion form submissions](https://user-images.githubusercontent.com/3376957/174128622-c19095f0-c08d-415a-bee1-fe2124f00664.png)

Also, I wonder how the admin currently reviews for duplicates before creating a new entry?  Is that something we can help with here, like a ‘search for similar’ button/feature perhaps?

We don’t have many suggestions in the LA area but I can imagine that there’ll be lots more in the future as we start supporting other regions.

**Comment by sei1122** [comment]
I updated the user flow and designed key pages.
Hope we can find a simple design solution and test user flow. 

Figma file link
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5680%3A9463


user flow
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5524%3A9295
<img width="1282" alt="Screen Shot 2022-06-21 at 9 36 46 PM" src="https://user-images.githubusercontent.com/19811032/174944480-7022e114-f370-417e-aaef-1244b3106d86.png">


design
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5680%3A9463
<img width="1416" alt="Screen Shot 2022-06-21 at 9 37 38 PM" src="https://user-images.githubusercontent.com/19811032/174944565-20b599ea-7c8c-451f-8ccd-1ab64255d145.png">

**Comment by sei1122** [comment]
@entrotech, @fancyham 
Here is the final of the Suggested Correction's Flow and Design. I wrote comments on the Figma file. 
Let me know if you need anything. 

<img width="515" alt="Screen Shot 2022-07-07 at 12 57 21 PM" src="https://user-images.githubusercontent.com/19811032/177861089-6350cc05-115b-4ad6-a53b-ccc4fc6de8db.png">

Figma file
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5876%3A9657

**Comment by sei1122** [comment]
Based on last week's meeting, I created 2 design ideas. 
1. Use the current dashboard and detail view modal and redesign them.
2. One-page style - this design doesn't use a dashboard.

<img width="552" alt="Screen Shot 2022-07-14 at 3 12 03 PM" src="https://user-images.githubusercontent.com/19811032/179097334-70cc9ca3-9aa6-4022-a4bc-bb4468fdef34.png">

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5936%3A9568

Things to consider
1 How the admin checks the duplication before creating the new org data? 
Idea: “Search for similar” button feature. Check by org name?

2 Click Create button and auto fill the data from tipster. How to handle the business hours?
Idea: Have notification on business hours page. 

3 Check Status Handling
-> We need New, Reject, Created, Accepted
Create State diagram

4 When the verification is completed, is it possible auto change the status on Suggestion dashboard so that admin doesn’t
need to come back. Also, this prevents from multiple checking the org status that have already verified.   
-> how to match up the data? use ID?

**Comment by sei1122** [comment]
Last week, we talked about using these 3 states: New, Created, and Rejected. However, when I made a state diagram, I found out we need to have one more status that handles the completion of the states. 

Here is the state diagram 
<img width="588" alt="Screen Shot 2022-07-14 at 3 20 30 PM" src="https://user-images.githubusercontent.com/19811032/179098179-e127da5c-1edf-42b2-ab92-c09029d26fa6.png">
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5965%3A10892

**Comment by sei1122** [comment]
Based on the last week's feedback, I updated the cross-functional user flow and the designs. 
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=4982%3A9019

**Things to consider**
- Is there a good way to check the duplicated org?
- If the admin finds duplicated org but there is new info from a tipster, how admin communicate this to a volunteer? e.g via email or chat?
- Search for a similar button feature to check by org name, phone, or address?
- When clicking the “Create Listing”, is it possible to auto change the status from New to Create?
- After the click Create Listing, is it possible to autofill?
- Business hours probably can’t autofill. Create a notification on top of the business hours page? 

**Current duplicated org check**
- I tested how currently can check the duplicated org. We need to use the **Criteria** button and find by name. 

<img width="616" alt="Screen Shot 2022-07-21 at 9 38 49 AM" src="https://user-images.githubusercontent.com/19811032/180267724-6b58c648-259a-4ded-9587-ce49762b3201.png">

**Comment by fancyham** [comment]
For “If the admin finds duplicated org but there is new info from a tipster, how admin communicate this to a volunteer? e.g via email or chat?”

Perhaps your new ‘suggestions’ flow could be useful for this — basically admin could convert the new listing info into a suggestion (or write a new one): 
> Add a button on the database’s org editing page called “add a note” which adds a suggestion from that user (Jordan in this case) to the organization.  Perhaps this button only appears for the admin at first?
> This spawns a new window with a blank suggestion tied to this organization (similar to the existing public suggestion form).  This form is pre-populated with the user’s account info, and the record might even flag this suggestion as coming from a back-end user, which would help with validation.
> This would create a new ‘suggestion’ that then appears at the top of the org editing screen next to any other suggestions where a future volunteer can resolve it.

**Comment by staceyrebekahscott** [comment]
@fancyham @sei1122 What are the next actions that should be taken to move this forward, as per the comment above? 

- Does this need approval for next steps? If so, it should be moved to the Questions/In Review column
- Does the Dev team need to do work on this?

**Comment by sei1122** [comment]
@staceyrebekahscott, 
Here is an update based on this week's meeting.
This issue has 2 sections. 
1. org data correction
(https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=5876%3A9657)

<img width="433" alt="Screen Shot 2022-07-30 at 9 59 29 AM" src="https://user-images.githubusercontent.com/19811032/181933939-796ccd71-c24c-457c-b5a7-743394e487f1.png">

2. suggest a new listing
(https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=6193%3A10693)
<img width="349" alt="Screen Shot 2022-07-30 at 9 59 46 AM" src="https://user-images.githubusercontent.com/19811032/181933948-8db0bfd9-ddee-467c-8563-98abe73409eb.png">

We completed the design of the 1.org data correction. We reviewed this design with John H and sent it to development. 
We are still working on the 2. suggest a new listing design.

**Comment by entrotech** [comment]
For corrections to existing listings, created development Issue #1271, #1272, #1273

**Comment by sei1122** [comment]
Here is a note about how to do  
**Suggest a new listing**

I asked @entrotech about which he thinks better. 
1. Design all the features and send them to development.
2. Make a happy path/MVP first and add features later.


Here is from John 
I'd say the first step is to get @rylantalerico involved in reviewing the proposed flow.  After that, in the spirit of agile development, I think we could create a series of incremental features starting with the ability to create a new listing by selecting a suggestion from the Suggest New Listing dashboard and having a button to push that creates a new listing and opens the OrganizationEdit form on the new listing.  It would pre-fill the fields that can be copied from the suggestion, and perhaps show the few fields that cannot be copied directly, like business hours, category, etc. in some sort of panel (similar to how unprocessed suggestions are to be shown for corrections to an existing listing). For this first iteration, the admin would have to manually do queries to check to make sure it isn't a duplicate. The initial status of the new listing would be "Needs Verification", and the admin could do the initial verification personally, or assign it to a volunteer, and then optionally provide verification notes as instructions to the volunteer.  If we just implement this and let Jordan Smith try it out first before we do anything more elaborate.

**Comment by staceyrebekahscott** [comment]
Moving to Questions/ In Review pending Rylan's response to the comment above.

**Comment by sei1122** [comment]
I updated the Figma file for MVP and wrote the points need to be clarify with team. Next step is to discuss the interaction and design with @entrotech, @fancyham, and @rylantalerico and finalize. 

https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=6426%3A11578
<img width="1144" alt="Screen Shot 2022-08-15 at 10 52 06 AM" src="https://user-images.githubusercontent.com/19811032/184688736-6d06ad7f-5e07-4f6e-a1ee-5230b9ae71be.png">

**Comment by staceyrebekahscott** [comment]
I attended the design meeting this afternoon (Wed, Sept 7, 2022) and was brought up to speed on the interaction and design. I  give PM approval to proceed with Dev tasks.

**Comment by sei1122** [comment]
I updated the design based on yesterday's review. 
I think this is good for now. When the dev team finished part 1 (Correction section), we can come back and review it again. 
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=6426%3A11913

<img width="1843" alt="Screen Shot 2022-09-08 at 2 17 18 PM" src="https://user-images.githubusercontent.com/19811032/189227580-14e68014-c50f-44e7-af42-380dc6fd34fa.png">

**Comment by itserindean** [comment]
Should this be merged with #996?

**Comment by staceyrebekahscott** [comment]
@sei1122 @fancyham Have you followed up with the Dev team on part 1- correction section, as noted in the comment above? What is the status on their work?

**Comment by sei1122** [comment]
I will follow up

**Comment by sei1122** [comment]
Here is from @entrotech 
"Development hasn't started on this issue. The devs are trying to button up a significant internal project in the next week or so, then we will start on new feature issues like this one."

**Comment by fancyham** [comment]
- Issue #996 has a **proposed non-MVP** corrections form (see below)..  if that's built, that would probably have some impact on this suggestions admin flow: 
- Would probably make some things easier for validation volunteers
- How to track and represent those suggestions? (perhaps a suggestion is automatically created that summarizes the proposed changes, along with draft database changes… that can be easily approved by the validator?)

It's also possible (perhaps likely) that we'll start out by using a free-form corrections form, and build this dream corrections interface later, once we've proven and streamlined #996's flows.

Sketch of the #996's proposed corrections form:
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-%231?node-id=8272%3A14553&t=VyVJUDNq4jslGEKW-4
![Screenshot 2023-02-17 at 11 01 48 AM](https://user-images.githubusercontent.com/3376957/219766452-9e850c3a-ba25-4292-acd8-8266d895640a.jpg)

**Comment by fancyham** [comment]
Quick update:

prioritization

These two related issues were evaluated together along with current priorities and knowledge

- #996
- #1131

Now that Erin (Product Manager) has brought managing volunteer updates in-house with UCLA student volunteers (which has been working amazing. Previously it was managed and run by LA Works), we now have the benefit of direct experience with updates and suggestions.

- Suggestions seem to be a doable manually without building much, so is lower priority
- What’s most useful right now is to prioritize the self-service corrections feature from #996, so putting this issue on the back burner for now and focusing efforts there.

**Comment by qiqicodes** [comment]
@JohnHaoHuang Here is the ongoing conversation regarding the redesign of the Suggestion Dashboard. 

We, the developers, are addressing an ongoing issue with the Suggestion Dashboard as outlined in issue #2121. We've noticed that the dashboard currently does not display correction data, and it's not possible to differentiate whether the data originates from the correction form or the suggestion form.

To effectively bridge these gaps until the full redesign is implemented, we propose adding additional columns temporarily. This modification will help ensure that all necessary data is captured during this interim period.

Please keep us informed about the progress of the new design and let us know when it is ready for implementation.

**Comment by fancyham** [comment]
Hi, I think that adding additional columns temporarily will work in the interim.  The goal is to capture and expose all that info so updates can be made more easily, so steps in that direction are great.

**Comment by farahrobleh** [comment]
@gigicobos @fancyham As we're looking organize our milestones, we're seeking clarification on this particular issue: what is the current state of the Suggestions page/Suggestions Administration board and modals, and would this be considered expanding on an existing feature, or creating a new one?

**Comment by ExperimentsInHonesty** [comment]
Review this issue, and integrate a new issue being opened on the repo when there is a new listing to review.

**Comment by fancyham** [comment]
This is expanding on an existing feature.

This might be incremental — at the very least, we should add some dates to the existing suggestions interface.

**Comment by fancyham** [comment]
Re: Product team's feedback and requests from here: https://github.com/hackforla/food-oasis/issues/1273#issuecomment-2964669651

Good comments... Replies below.  Also, these comments belong in this issue, not really here:
- #1131 

[Suggestions admin board figma](https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=5311-9208&t=aWi6OTEv5AdwlZE3-4)

> 1. On the mockups for Suggestion Administration
>       - A. add Tipster Name 

Yes, and we should also add email address

>       - B change the status label "New" to "Unprocessed" and add Processing

- Yes to change "New" to "Unprocessed"
- Question: Rather than adding a new state "Processing" we should probably use the existing state "Pending" and rename it to "Processing", right?  
![Image](https://github.com/user-attachments/assets/d6767221-1786-43f2-999f-4194c2c7697e)
([link](https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=5350-9191&t=aWi6OTEv5AdwlZE3-4)) 

> 2. [On the mockups for New Listing Modal](https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=6426-11578&t=aWi6OTEv5AdwlZE3-4)
>       - A. have an area where it compares each field with existing fields in database and if there is similar, provides links (e.g., if the address is the same address as another pantry, that would show up in the comparison field next to address and be clickable so that you could see the other listing a new window)
> 

- Org name: How about showing to orgs with similar names under the org name field.  What counts as 'similar'?  Dev team will have to give feedback on what's possible, but we can put something in the design.

- Address: If address is not exact, we'd still want to show orgs with similar addresses.  Again, need to ask dev what's possible, but we can put it in designs.

> - B. confirming that the conversion from suggested new listing to an actual new listing, happens when you change status to "Accepted" which would queue it up for validation.

I don't think that's how it works — Could you clarify?  

Currently, 'Suggested New' listings have a different set of states than 'Suggest Correction'

Suggest New listing item statuses: New, Rejected, Created
Suggest Correction item statuses: New, Pending, Rejected, Accepted (currently called Closed)

Looking at the diagram, I believe a new listing is created when user presses the "create listing" button here, or they could manually create one in a different window and change the status drop-down.  

![Image](https://github.com/user-attachments/assets/c25a3c70-13f5-43b4-94b3-cd80e0ebd317)

([figma](https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=6441-10987&t=aWi6OTEv5AdwlZE3-4))


> 3. On the mockups for Correction Modal
>       - there isn't a one-to-one relationship between fields in a listing and this modal.  The information is all tied up in the suggestion field. So we need a way to get it on to the listing.  I suggest we add it as an admin note, to be processed, or if you want it some other way, please indicate with design.

I believe we're already storing a record of the original suggestion in the proposed history log:

![Image](https://github.com/user-attachments/assets/75fcf0f1-5658-4368-b969-7496c45572c5)

([figma](https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=6911-11402&t=aWi6OTEv5AdwlZE3-4))

Does that satisfy this request?

Also, longer-term, please consider how we might be able to make an abbreviated internal database editing UI available to the public and orgs.  

Talk to me if you want some sketches of how this might work.  I've been thinking about it, but would require some significant changes.  This ticketing system I think would be part of it, but imagine replacing the fields we have now with a simplified version of our org editing UI.

**Comment by TifNi** [comment]
@fancyham Please add the prioritization label to this. We will look at MUST HAVE tomorrow.

**Comment by fancyham** [comment]
Updated the Suggestions Admin board:

Did not change "New" to "Unprocessed" -- this ends up being confusing with the submission status appearing different ways to different users.  New items are "New" for everyone until the start becoming Pending.

Also, [I simplified how a suggestion's status is tracked](https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=13309-39197&t=10kYMh2I5T5fApVl-4)... We are adding new states to track tickets in-progress, so rather than introduce a new state variable, let's expand the original one so it works across the entire lifespan of a suggestion.

> DEVELOPERS:
> I combined two separate state variables into a single one that tracks the progress of a suggestion through its lifecycle.
> 
> Suggestion is submitted by the public:
> “Unprocessed AKA New” - A suggestion that hasn’t been acted on yet, and that will appear atop the Org Edit screen for everyone. Admin sees “Unprocessed/New”, Validator sees “New”
> 
> Suggestion has been edited on the org editing interface:
> “Pending acceptance (Marked as Confirmed)” AKA “Confirmed” - Validator has confirmed the suggestion, but admin hasn’t accepted the org changes yet.. Admin sees “Pending (Confirmed)”, Validator sees “Confirmed”
> “Pending acceptance (Marked as Incorrect)” AKA “Incorrect” -  Validator indiciates that the suggestion is incorrect, but admin hasn’t accepted the org changes yet. Admin sees “Pending (Incorrect)”, Validator sees “Incorrect”
> 
> Org data has been ‘accepted’ by the administrator:
> “Accepted” - suggestions that have been marked as confirmed by the validator, then admin accepted the validator’s submission.  Admin sees “Accepted”
> “Rejected” - Marked as rejected by validator, then the org changes were ‘accepted’ by the administrator.  Admin sees “Rejected”

![Image](https://github.com/user-attachments/assets/a469c5bb-129d-4081-baab-d0c6576989e3)

Link to figma: https://www.figma.com/design/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design--1?node-id=13309-39192&t=10kYMh2I5T5fApVl-4

**Comment by fancyham** [comment]
Hi, this was marked 'ready for design lead' but I don't see anything actionable or requested, so I'm bouncing this back to product
