### ISSUE TITLE
FOLA: Agenda for PM/org meeting

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1135]
Links

### Bonnie x Ben - Last meetings
[Tuesday 2022-02-15](https://github.com/hackforla/food-oasis/issues/1135#issuecomment-1040562489)
### Overview
This issue tracks the agenda for the PM meetings for FOLA

Meeting takes place Tuesdays - 10 AM PST

#### Template
```
## 2022-00-00 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Label and milestone review and audit #1119
- [ ] Task items from previous week

### Items carried over from last meeting 
(Items we didn't have time for)


### New Items

- [ ] 

### FYIs
- 

### Notes during meeting
-

### Task Items

### Items for next meeting 
(these are new items surfaced during this meeting that go into new items on next agenda)
```

**Comment by ExperimentsInHonesty** [comment]
## Agenda and MoM PM/Org meeting 2021-12-14

### Prework

### New Items

### Items for next week
- [ ] Follow up with what ends up happening on this issue #1065.  Its less about the specific issue and more about how to put things in the icebox.

**Comment by Benbaillou** [comment]
Agenda and MoM PM/Org meeting 2021-12-14

### New Items

- [ ] Issue audit Follow-up: Label and milestone review and audit #1119
- [ ] Personal advise on getting more technical expertise

### General Notes



### Items for next meeting

- [ ]  Follow up with what ends up happening on this issue Investigate Improved Time Pickers for Business Hours #1065. Its less about the specific issue and more about how to put things in the icebox.
- [ ]  work on roadmap together
- [ ]  Ben will work with John and Gigi to make a meeting with the point of contact from LA Works
- [ ] Agenda for meeting: understand what their contribution is, how it fits into the partnership plans, strategic plans and overall mission and goals for the org. Purpose for the meeting is to understand them, so that we can better alignment in the future (emphasis on future, the meeting is not to discuss our plans)

**Comment by ExperimentsInHonesty** [comment]
2022- 01-011 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Label and milestone review and audit #1119

### Items carried over from last meeting
- [ ]  work on roadmap together
- [ ]  Ben will work with John and Gigi to make a meeting with the point of contact from LA Works
  - [ ] Agenda for meeting: understand what their contribution is, how it fits into the partnership plans, strategic plans and overall mission and goals for the org. Purpose for the meeting is to understand them, so that we can better alignment in the future (emphasis on future, the meeting is not to discuss our plans)

### General Notes


### Task Items

### Items for next meeting

**Comment by Benbaillou** [comment]
## 2022-01-13 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Label and milestone review and audit #1119
- [ ] Task items from previous week

### Items carried over from last meeting


### New Items

- [ ] 

### FYI
Contact at LA Works for Bonnie to organise a meeting to discuss the current partnership between our 2 organisations: [Denise Vi Flaten - Program Manager](https://www.linkedin.com/in/denise-vi-flaten/) email: denise@laworks.com. Note: put Jordan Smith in copy of the email (our current point of contact at LA Works in copy of the email - jsmith2009@gmail.com)

### General Notes
-

### Task Items

### Items for next meeting

**Comment by Benbaillou** [comment]
## 2022-01-13  Gigi x Ben Meeting

### Task Items
- **Ben**: 

- [ ] to write draft email for Bonnie
- [ ] to update Automate the selection of organisations to review - Organisation Form #1150 and #834 

- **Gigi**: 

- [ ] to update #679 

- **Gigi and Ben**:

- [ ] Set an ad hoc meeting with John w/c 17 Jan to discuss new issues, updates and to size issue in the ""Prioritized Backlog"
- [ ] select potential issues from "Prioritized Backlog" to " New issue for approval" in order to tide the dashboard

**Comment by Benbaillou** [comment]
# 2022-01-18 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Label and milestone review and audit #1119 
- [ ] Task items from previous week: 
    - [ ] email for LA WORK

### Items carried over from last meeting

### New Items

- [ ] Slack chatbox to update Team meeting 

### General Notes
-

### Task Items

### Items for next meeting
[ ] Label and milestone review and audit #1119

**Comment by Benbaillou** [comment]
## 2022-01-25 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Label and milestone review and audit #1119
- [ ] Task items from previous week

### Items carried over from last meeting


### New Items

- [ ] Redefine HFLA expectations for Food Oasis

### FYIs
- 

### Notes during meeting
-

### Task Items

### Items for next meeting

**Comment by ExperimentsInHonesty** [comment]
Add to next agenda
- [ ] Is this role filled? https://github.com/hackforla/product-management/projects/8#card-74728050, if yes, move to filled, if no, discuss.

**Comment by Benbaillou** [comment]
## 2022-00-00 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Label and milestone review and audit #1119
- [ ] Change Fola team meeting on VRMS

### Items carried over from last meeting


### New Items

- [ ] 

### FYIs
- 

### Notes during meeting
-

### Task Items

### Items for next meeting

**Comment by Benbaillou** [comment]
## 2022-02-08 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Label and milestone review and audit #1119
- [ ] Ben to reach out to Tina Mo to ask her to change the owner of this [figma file](https://www.figma.com/files/team/1050838049378816186/FOLA/members?fuid=775836858007206739) to [foodoasisinfo@hackforla.org](mailto:foodoasisinfo@hackforla.org)

### Items carried over from last meeting 
(Items we didn't have time for)

- [ ] [FOLA Roadmap/milestone review](https://github.com/hackforla/food-oasis/projects/8)

### New Items
- [ ] Following LA Works meeting
  - [ ] Decide a strategy to make sure LA W. does not deprioritize their support on FOLA 
  - [ ] Create a pitch/deck to present to LA W. - deadline 2 weeks
- [ ] Ben - Offer received for a PM role. Question: how to get a reference from FOLA?
### FYIs
- 

### Notes during meeting
-

### Task Items
Tina Mo to ask her to change the owner of this [figma file](https://www.figma.com/files/team/1050838049378816186/FOLA/members?fuid=775836858007206739) to [foodoasisinfo@hackforla.org](mailto:foodoasisinfo@hackforla.org)

### Items for next meeting 
(these are new items surfaced during this meeting that go into new items on next agenda)

**Comment by Benbaillou** [comment]
## 2022-02-00 Agenda and MoM PM/Org meeting 

### Prework
- [ ] Contact Clara Buck from Win App
- [ ] Label and milestone review and audit #1119
- [ ] Ben and Gigi to update the [deck](https://docs.google.com/presentation/d/1pKv3Frjcadu6XYBsN55D9OmsnDDGy_gblA1hs_IWiKA/edit#slide=id.g7353973022_1_0) + [training deck](https://docs.google.com/presentation/d/1dMoBhJQM-JmTA-n4DQn_9HO0wEXlick5VfJa-PN_Efg/edit#slide=id.g52d92714eb_1_14) + add a slide on " we value all people that gives us time...." => LA Works to appear on the slide.
- [ ] Tina Mo to ask her to change the owner of this [figma file](https://www.figma.com/files/team/1050838049378816186/FOLA/members?fuid=775836858007206739) to [foodoasisinfo@hackforla.org](mailto:foodoasisinfo@hackforla.org)

### Items carried over from last meeting 
(Items we didn't have time for)


### New Items

- [ ] Seiko - our designer is here today to discuss #1129 and #1140 

### FYIs
- 

### Notes during meeting
-

### Task Items

### Items for next meeting 
(these are new items surfaced during this meeting that go into new items on next agenda)

**Comment by staceyrebekahscott** [comment]
Closing this issue, as we now use an on going doc to keep team meeting notes, and that process works well for the team.
