### ISSUE TITLE
UX Benchmarking

### ISSUE THREAD

**Issue by ryu-jieun** [hackforla/food-oasis#1144]
### Overview
In order to measure the effectiveness and impact of UX research and to track the overall progress of Food Oasis sites, we would like to discuss what and how to measure them. 

### Action Items

- [ ] Write a short context paper on why we need UX benchmarking 
- [x] #1146
- [ ] #1147

Related to (or might replace)
- [ ] #1127

**Comment by ExperimentsInHonesty** [comment]
@LIlinit
@ryu-jieun

I have turned this issue into an epic, because it is too big for one issue.  I have created two new blank issues and linked them. Please fill those issues out.  All issues on the site, across all practice areas, need to be separated into food seeker and volunteer  issues respectively so that they can be managed by their respective PMs

Also, the user story that is present in the overview above is not clear enough for people other than yourselves to understand how we will know when this issue is done or what exactly should go into it.  

Please let Ben know when you have revised this issue and its sub issues.

**Comment by fancyham** [comment]
Some actions we can take that we discussed today and noting them here.  Maybe move these to sub-tasks or to issue description at top?

- [ ]   Review what analytics packages we currently have (might review source code of site — I saw only Firebase Analytics (AKA Google Analytics)
- [ ]   Get everyone interested access to those analytics
- [ ]   Discuss among team what stats are useful for us
- [ ]   Identify gap between what we have currently and what we want
- [ ]   Implement what we can

**Comment by staceyrebekahscott** [comment]
Website Analytics needs to be made a priority as we are moving towards adding Food Oasis on more websites. Making this a goal of the Impact Sprints and moving to Prioritized Backlog.

**Comment by staceyrebekahscott** [comment]
@GigiUxR I see you reopened this issue after it was closed and put in the Done column. I moved it back to the Backlog column. Keep in mind that there is no automation to put the issue back in the correct priority, so if you reopen an issue, you must manually reprioritize it.

**Comment by GigiUxR** [comment]
@staceyrebekahscott to inquire about resources / guides specific to nonprofit UX Benchmarking
 Waiting for Tyler to get onboarded then assign this issue to him.

**Comment by staceyrebekahscott** [comment]
I posted a message on the Code for America # general-discussion Slack channel, seeking advice/ guidance on benchmarking for public/ non profit.

**Comment by staceyrebekahscott** [comment]
FYI, here is the conversation from the UX Benchmarking question I posted on the CfA Slack:

Stacey (she/her)  [4:47 PM]
Hello! Does anyone have any advice/ guidance regarding UX Benchmarking for websites in the Non Profit sector? I ask assuming there might be different criteria to consider for non profit/ public sector vs. commercial/ private sector.

Ray Kiddy  [4:54 PM]
UX Benchmarking would be similar to commercial efforts. The differing goals would drive differences in benchmarking. For example, commercial and non-profits would measure session length (# pages visited) but the NP would be oriented to helping a user goal and not driving users to the checkout. What is the audience. Differently-abled people might prefer more of a focus on site simplification and ADA compliance.

Stacey (she/her)  [5:19 PM]
So, there's not a difference in the process of benchmarking, it's that the measurements of success would be different based on goals.

Stacey (she/her)  [5:21 PM]
Our website is a food pantry locator, so the audience would cross many different demographics.

Chris Eberhardt  [5:57 PM]
Yes, I was going to say, it would be a good thing to be 508 compliant.

**Comment by staceyrebekahscott** [comment]
@GigiUxR Moved to In Progress. Will leave to you to assign to the researchers once you go through the kanban board/ issue workflow training.

**Comment by fancyham** [comment]
FYI, on a related DEI note: I created an Accessibility benchmarking issue here for the food-seeker site:
- #1355

**Comment by ToledoPHD** [comment]
1. Created "what is UX benchmarking" presentation and context paper.
2. Created [spreadsheet](https://docs.google.com/spreadsheets/d/1yM2SeeJKhM4GH8iKltIDjgjpsA0KXJyu/edit?usp=sharing&ouid=118407023390464418749&rtpof=true&sd=true) to help identify UX benchmark priorities and metric opportunities focused on: web analytics, volunteer user testing/survey, and food seeker testing/survey.
3. Prioritized web analytics and volunteer benchmarking. 
4. Will meet with analytics team to establish metrics. 
5. Will meet with research lead + current team to determine timeline and most relevant metrics before establishing research plan for volunteer benchmarking. 
[Context Paper.v2.docx.pdf](https://github.com/hackforla/food-oasis/files/9883884/Context.Paper.v2.docx.pdf)
[UX_Benchmarking_Presentation_10_13_2022.pdf](https://github.com/hackforla/food-oasis/files/9883885/UX_Benchmarking_Presentation_10_13_2022.pdf)
