### ISSUE TITLE
2022 FOLA Team Meeting Agenda

### ISSUE THREAD

**Issue by Benbaillou** [hackforla/food-oasis#1158]
### Overview
This issue tracks the agenda for the product management community of practice and weekly roll calls for projects.

[Feb 3 2022](https://github.com/hackforla/food-oasis/issues/1158#issuecomment-1029412844)

[### Google form - Agenda Suggestion - to edit
](https://docs.google.com/document/d/1-q3ch3gQJLNut9n6-Y_W_jI-1vVDYNEXwyB1wNWqbVM/edit)

- For meeting agendas before June 2021, please check the [2021 [FOLA] Team Meeting Agenda document](https://docs.google.com/document/d/1Rc-E-n51uui4SDW8RFM41RTLvPmsNe7MMpZ9HYi3LTM/edit#heading=h.4dpwpbnif7si)
- For meeting agendas after June 2021 to December 2021, please check the #1014 

### template
```
## Date

### Prework
### Items from last meeting
### New items
### General Notes
### Task items
### Items for next meeting
```

**Last meeting links**

**Comment by Benbaillou** [comment]
## 03 Feb 2022

### Prework
### Items from last meeting
### New items

- [ ] Shewta had to leave the USA and FOLA due to family issue
- [ ] **Bonnie**: we need to prepare the meeting between LA Works (Dennise) and us
- [ ] **Gigi P**:  to discuss the current updates and the needs of UX Researchers
- [ ] **Ben**: present milestones and 'how to get things done' for Food Oasis
- [ ] **team**: discuss 2 issues: #1150 and #834 

### General Notes
### Task items

- [ ] **Team**: complete the issue #1155 to assess which issues are **outdated** or **duplicated** and that we can close
- [ ] **Team**: complete the poll for Design and Development meeting

### Items for next meeting

**Comment by staceyrebekahscott** [comment]
Closing this issue, as we use an on going doc for team meeting notes, and that process works well for the team.
