### ISSUE TITLE
Empower LA Data 

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1341]
### Overview

The LA Neighborhood Councils (NCs), under Empower LA, have committees and
priorities that they manage on behalf of their constituents. They have influence in their
communities and partnering with them to have the Food Oasis tool embedded on their
websites is a way for Food Oasis to expand its reach and help more people. 
(more info: [Neighborhood Councils Partnership Strategy for Impact Sprints 2022](https://docs.google.com/document/d/1UVv6pT7Y1hjLELp9yhwfK1l4IElbm6Qc499-AqB2VV4/edit))

**Dependent Issues**
#1291 Partnership Engagement: Los Feliz Neighborhood Council
#1301 Hack for LA projects with current relationships with LA Neighborhood Councils

Goal: 
Get our Embed on all NCs with Food Pantries listed on their sites, or some mention of food resources or food related outreach

### Action Items

- [x] Fill in spreadsheet marking NCs that have Food Resources listed or Food Insecurity as a priority
- [x] Review Empower LA data
- [x] Develop a strategy for reaching out to NCs with Food Insecurity as their focus 
- [x] Add to NCs with Food Focus tab on spreadsheet
  - [x] NC Leadership & Email Addresses
  - [x] Other Areas of Focus
  - [x] Idea(s) for how to introduce our idea to embed Food Oasis tool onto their NC website
- [x] Draft emails to send to NC Leadership 

[NCs with Pantries or Food Insecurity as a focus](https://docs.google.com/spreadsheets/d/1c7adTrb9nF3f9YDwKZSaoBWGQVfadKklP8I8Dq6-wZ4/edit#gid=0
)

Data  collected Oct 21-Jan 22 re: concerns of NC constituents. Access to adequate food was approx 1%.  https://empowerla.org/data/

- This issue has been turned into an Epic. 
- Once we connect with an NC and they are interested in speaking with us, we will need to evaluate whether our embed will work on their site. This website lists all tech used by NCs: [OCS: Builtwith data on 99 NCs technologies
](https://docs.google.com/spreadsheets/d/1gvlBd-tragQmT1oblX560-EWbDXYzrcqVDUhyIzHWa0/edit#gid=1851194011)
  - If so, we will need to organize an easy process for their Web master to add it to their site or offer our assistance to complete this task. 
- As part of the engagement, we will need access to their website analytics so we can track the number of users accessing the embed. 
- If the embed does not work on their site, then we can discuss adding information and a link to our website as part of their food resources listings. 
- We should design a flyer that NCs can print and hand out at community events

**Comment by staceyrebekahscott** [comment]
@itserindean @yiminng @rylantalerico I could use some help on this one. I created a spreadsheet with all the neighborhood councils listed. I am adding details for the ones that list any kind of food resources or list food insecurity as a focus. I am recommending we reach out to those NCs first to see how interested they are in our embed. 

On the sheet, the NC name links to the Empower LA website, and on that page there is a link to the NCs website. I've been checking the main page, the committees, the resources page, anywhere where I think food resources would be listed. And I've added notes to the column next to it. 

If you have some time and can check any of these that would be helpful. Thanks!

**Comment by staceyrebekahscott** [comment]
@bkobak33 @jelenaUX @cheesarah Please see the comment above for instructions on what to do. Thanks for your help!!

**Comment by staceyrebekahscott** [comment]
@miolow As per my message in Slack, please see the comment above from last Thursday for an explanation on what needs to be done. Your assistance would be appreciated.

**Comment by fancyham** [comment]
For future reference, NC = Los angeles neighborhood council
https://empowerla.org/about-neighborhood-councils/

@staceyrebekahscott could you add to the description of this issue to flesh out what this means for those not already familiar?
> Discuss and evaluate whether this is strategically viable. Establish what would constitute success, and how much effort to put forth.

**Comment by staceyrebekahscott** [comment]
[Neighborhood Councils Partnership Strategy for Impact Sprints 2022](https://docs.google.com/document/d/1UVv6pT7Y1hjLELp9yhwfK1l4IElbm6Qc499-AqB2VV4/edit)
Link also in Overview 

This details the strategy for the Neighborhood Councils Partnership, including success measures, challenges and next steps.

**Comment by staceyrebekahscott** [comment]
@isaella @cheesarah I created a second tab on the NCs spreadsheet, and added only the NCs identified as having food resources on their site. I'd like to do further research into these NCs. I've added columns for Leadership, other NC priorities and thoughts on how to engage with them. This last column I'd appreciate any ideas you have as you are looking through their websites that might be useful to include in a request for partnership email. I've highlighted 2 NCs that I would like to start with, but the idea is to draft emails for all of them, get approval from HfLA leadership, send them out and see who responds. 

The next part of the partnership plan will be to work with the Dev team to confirm our embed will work on the NC's website, to prepare instructions for the embed and figure out any tech support we can offer. We will also need to have access to their analytics so we can track how often the embed is being used. 

And then from there we would like to work out some cadence for regular follow up with the NCs we partner with. Eventually perhaps we might have a partnership page on our website.

**Comment by fancyham** [comment]
@staceyrebekahscott FYI, the document with the background of this issue "[Neighborhood Councils Partnership Strategy for Impact Sprints 2022](https://docs.google.com/document/d/1UVv6pT7Y1hjLELp9yhwfK1l4IElbm6Qc499-AqB2VV4/edit)" looks like it's about to be deleted.

I added the first part of that document to this issue's description so that it's easy to follow and in case the file goes missing/gets changed.

**Comment by staceyrebekahscott** [comment]
@fancyham Thank you for bringing my attention to the document being deleted. I removed it from the trash. And thank you for adding details to the issue description.

**Comment by staceyrebekahscott** [comment]
Drafted emails for ECWANDC and MINC, sent to Mellina Stoney for review.

**Comment by staceyrebekahscott** [comment]
Received feedback from Mellina, made corrections and added drafts to FOLA's Drive. Sent links to Leads/PM and Sam for feedback. 

[ECWANDC Partnership Letter 10/24/22](https://docs.google.com/document/d/1hnr9ljV6-9YZrsyB0jiB-mjFxZCnpYwiOXjpT1sGNmA/edit#)
[MINC Partnership Letter 10/24/22](https://docs.google.com/document/d/1haa0dvSQDSQ1c9pc9259UZkON2Tj3VEr2zXhZH54pbc/edit#)

**Comment by staceyrebekahscott** [comment]
Reviewed language with the team and made recommended updates. Goal is to send out the first correspondence this week, and to incorporate the NCs into the partnership engagement roadmap.

**Comment by staceyrebekahscott** [comment]
Emails sent to ECWANDC and MINC.

**Comment by staceyrebekahscott** [comment]
Copied from my message in the FOLA PMs channel in Slack:

I found this as part of my NC research: [Neighborhood Purpose Grants](https://hcnnc.org/how-to-apply-for-neighborhood-purpose-grants-npgs/)

Bonnie has mentioned these before, but with no other details, and I could not find anything in our Drive, so I just Googled.

The timeline for this might work out well for us. They issue these grants towards the end of their fiscal year, which must be in June, as they start issuing these grants in March-May. This gives me some incentive to proceed fully with the outreach strategy I am developing- to start sending out the partnership request emails now and hopefully start working with a few of the NCs before March, so we might be eligible to apply.

I will also continue working with Jess at Code for America to get the proper documentation in order in advance.

**Comment by staceyrebekahscott** [comment]
Sent a follow up email to Gina Fields at ECWANDC.

**Comment by staceyrebekahscott** [comment]
Update I shared on Slack:

FYI, I followed up with Gina Fields from the ECWANDC Neighborhood council. This is the one that covers my neighborhood. She responded that she was available for a call this afternoon. I did reach out to her and left her a message, but we were unable to connect today. I followed up to see if we could chat tomorrow or Wednesday.

**Comment by staceyrebekahscott** [comment]
Based on recent conversations in PM and Leads meetings, we are considering a new partnership in working with colleges and universities. 

It might be a viable marketing campaign to reach out to the neighborhood councils to have Food Oasis listed on their site. But that would be a new issue and project handled by a marketing focused team. I would leave it to them to decide if that is a worthwhile endeavor. 

In the meantime, I will work on an evaluation of the outreach efforts up until now and get feedback from the team as to how we should proceed.

**Comment by staceyrebekahscott** [comment]
Moving to Up next, will pick up work on this once Roadmapping is completed.
