### ISSUE TITLE
Roadmap and Strategy Development- 1st Quarter 2023

### ISSUE THREAD

**Issue by staceyrebekahscott** [hackforla/food-oasis#1535]
### Overview
The PM team is developing a roadmap using the Now, Next, Later roadmapping framework. 

We will then break out goals for Sprints and prioritize issues accordingly. 

### Action Items
- [x] Using Miro, build out roadmap draft and add initial high level priorities from current tasks. 
- [x] Brainstorm new ideas for adding to the Next and Later columns
- [x] Develop Sprint drafts of priorities in the Now column- will be handled by individual teams
- [x] Introduce Roadmap and Sprints to Leads team for feedback
- [x] Introduce Roadmap and Sprints to teams for feedback and further development

**Comment by staceyrebekahscott** [comment]
@itserindean Created issue for our roadmapping work.

**Comment by staceyrebekahscott** [comment]
@itserindean I think we should take some time to do a brief presentation of the roadmap to the team during the next All Hands. I think John D is going to present some Dev related work, so he should go first. But we should do a condensed version of what we presented tonight. We can discuss at our PM meeting next week.

**Comment by staceyrebekahscott** [comment]
Roadmap Presentation 02/16/23: [FOLA Roadmap 2023](https://docs.google.com/presentation/d/1koxPV6oF2H3J2b3HTiIF-NSWxBvw1yF7xjSv-pxC9tw/edit#slide=id.g173838d392e_0_0)
