### ISSUE TITLE
FOLA Content Team - Restart Checklist

### ISSUE THREAD

**Issue by bduhe** [hackforla/food-oasis#1823]
### Overview
This issue provides information on how to restart the FOLA Content Team.

### Action Items
- [ ] Read the [FOLA Content Team Restart Guide](https://docs.google.com/document/d/18H5r1uqj13T9H96uiP9wU6f7wokAU3-iCLewp4DgUck/edit) 
- [ ]  Review [FOLA Content Google Drive](https://drive.google.com/drive/folders/1EOr3xU_jMzA6Yz7cxaCUrGedsuVEOfuI)
- [ ] Review Open Git Issues: #1620, #1553, and #1554
- [ ] Plan next website content maintenance: #1587 
- [ ] Review Icebox Git Issues: #1633
