### ISSUE TITLE
Research: A review of what data we collect from our users, and what we can use to improve our site

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#2071]
### Overview

What data do we / can we collect from our users?  This is super useful for researchers and FO planning.

This small project would involve a researcher and a dev who can gather info about how we process user inputs (from the search field, from pressing buttons, etc.)

Usefulness: 4/5 (where 5 is extremely useful)

### Description

To help us improve our site, we’ve been relying on various analytics packages (like Google Analytics), but they are very difficult to use and actually, we have much better ways to learn about how our users use our site — by anonymously collecting what they enter into the search field, what orgs they view and share.

**So with that in mind, let’s do an audit of our capabilities:**
- What data do we currently collect about our users?
- What data can we collect about our users with some small changes/additions?

This project would probably involve a researcher talking to devs, perhaps John D, to learn about what we do and then evaluate level of difficulty of collecting additional data.

Along the way, this will likely spur some ideas for what data we can also collect or how we can use collected data to infer our user’s needs.  It could also be useful for Hack for LA data miners to report and help other food-provider organizations or government.

### Examples

- Do we / can we collect the addresses people are entering into the search field?  
- What are the most frequently accessed organizations?
- How can we omit FOLA volunteers from being counted in this collected data? (probably will be anyone who logs in to FOLA — set a long-lasting cookie that will omit that user’s browser)

### Discussion

Some thoughts about how we can use this data in our own analysis

- If we can collect address inputs and default languages, we can map that out to find out hotspots of need.  Cross-reference that with a population and language needs map, we can discover if we’re overlooking particular language needs.

- We may also able to find out if there are too-few food providers in certain areas.

- Hack for LA is already doing data-mining to show food provider deserts and the like.  They would surely love additional details if we can provide it.

### Action Items

So with that in mind, let’s do an audit of our capabilities:

#### Part 1: Audit
- [ ] What data do we currently collect about our users?  And how can we access it?
  - [ ] Search address?  Time and date?  IP geo-location?  Default language?  Number of orgs searched in a particular visit?
- [ ] What new data can we collect about our users with some small changes/additions (work with devs on this)?
- [ ] (optional) What data are currently impossible to collect and why? (for future reference)
- [ ] Write up a report to share with other researchers and the FOLA team

#### Part 2: Export data
- [ ] Figure out a way (with developers) to export or gather reports of the data that we’re currently collecting, so that it can be used for analysis by the research and perhaps marketing team (for example, to target certain languages)

At this point, this might spawn sub-projects:

#### Part 3: Build new capabilities, if there are things we want
- [ ] Create mini-projects to build new data collection capabilities (for example, the pop-up survey project #1769 )

### Resources/Instructions

This will involve working with devs and asking questions.  

One industry term for this is ‘instrumentation’ — i.e. instrumentation = tools we have built into the app that gathers metrics and measurements.  Like “what type of instrumentation do we have on our site?”, or ‘adding instrumentation’

**Comment by SAUMILDHANKAR** [comment]
- Personally I would say the traffic to the site is low and so maybe we should get help from a statistician about if we can significantly derive inference based on the number of site visits.
- If we want to improve users and then use their data for research maybe we can consider creating an issue about improving the traffic to this site and link this issue to that as a dependency. Food cycle, neighborhood councils can drive a lot of traffic and we can have something inhouse as well (but that will be long term)
- Definitely would need a person who knows what all is collected and how to access the report.
- Search bar is a great source of data about what seekers are looking for (not sure if it is recorded though)/ what if a person searches chicken soup which is invalid entry for our application but is it recorded)
- In addition to this issue resulting a report maybe we can also have documentation about how to what all is collected so the research team can work with that.
- I am not sure if it possible to get in touch with people who are using the site and request an interview through email but that would help research team a lot. (maybe impossible/future)
