### ISSUE TITLE
FOLA: PM/Org Agenda

### ISSUE THREAD

**Issue by farahrobleh** [hackforla/food-oasis#2228]
### Overview

This issue tracks the agenda for our weekly meetings

**Issue Template**

```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Tiffany
    - [ ] Alexa
    - [ ] Saumil

- [ ]  Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Alexa](https://github.com/hackforla/food-oasis/issues/assigned/Ray65)
       - [ ] [Saumil](https://github.com/hackforla/food-oasis/issues/assigned/SAUMILDHANKAR)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team

(so that you can easily post on their agendas items that come up at yours)

- #2227 
- #2226 
- #2209 
- #2418

**Comment by farahrobleh** [comment]
## 2024-09-25 Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Product+Management%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Robleh](https://github.com/hackforla/food-oasis/issues/assigned/farahrobleh)
       - [ ] [Sumit](https://github.com/hackforla/food-oasis/issues/assigned/sumit-sharma92)
       - [ ] [Muthamil](https://github.com/hackforla/food-oasis/issues/assigned/MuthamilselvanG)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by farahrobleh** [comment]
## 2024-10-02 Meeting Agenda

### Prework to prep for meeting
- [] Work on milestones (create new milestones, archive old ones, etc.).
- [] Refer to HfLA PM Community of Practice Milestone Link for details: Placeholder 

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Product+Management%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Robleh](https://github.com/hackforla/food-oasis/issues/assigned/farahrobleh)
       - [ ] [Sumit](https://github.com/hackforla/food-oasis/issues/assigned/sumit-sharma92)
       - [ ] [Muthamil](https://github.com/hackforla/food-oasis/issues/assigned/MuthamilselvanG)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] 

### FYIs
- N/A

### Notes from Meeting
- 

### Task Items

**Comment by farahrobleh** [comment]
## 2024-10-09 Meeting Agenda

### Prework to prep for meeting
- [ ] Continue working on milestones, check new Project Setup Milestone
- [ ] Refer to HfLA PM Community of Practice Milestone Link for details: [Link here](https://github.com/hackforla/product-management/wiki/Milestones) 

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Product+Management%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Robleh](https://github.com/hackforla/food-oasis/issues/assigned/farahrobleh)
       - [ ] [Sumit](https://github.com/hackforla/food-oasis/issues/assigned/sumit-sharma92)
       - [ ] [Muthamil](https://github.com/hackforla/food-oasis/issues/assigned/MuthamilselvanG)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] 

### FYIs
- N/A

### Notes from Meeting
- 

### Task Items

**Comment by farahrobleh** [comment]
## 2024-10-16 Meeting Agenda

### Prework to prep for meeting
- [x] Refer to live milestone issue
- [x] Refer to HfLA PM Community of Practice Milestone Link for details: [Link here](https://github.com/hackforla/product-management/wiki/Milestones)
- [x] Refer to Food Oasis Roadmap/Milestone/Spreadsheets 
- [ ] Continue to progress on sorting issues on Website Improvements (Impact Sprints 2022) milestone
- [ ] Check Reboot Partnership Engagement (Impact Sprints 2022) issue/make progress on that with the PM team https://github.com/hackforla/food-oasis/issues/2241
- [ ] Review Food Oasis Marketing Epic https://github.com/hackforla/marketing/issues/74

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Website+and+Marketing+Content%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - Roll Call
    - [ ] Robleh
    - [ ] Bonnie
    - [ ] Sumit
    - [ ] Muthamil
    - [ ] Nate
- [ ]  Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Robleh](https://github.com/hackforla/food-oasis/issues/assigned/farahrobleh)
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)
       - [ ] [Sumit](https://github.com/hackforla/food-oasis/issues/assigned/sumit-sharma92)
       - [ ] [Muthamil](https://github.com/hackforla/food-oasis/issues/assigned/MuthamilselvanG)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Review the milestone issue: https://github.com/hackforla/food-oasis/issues/2232
- [ ] Finish with Website Improvements (Impact Sprints 2022) milestone/sorting issues from that milestone into new milestones 
- [ ] Review the Partnership Engagement Issue
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
- 

### Task Items
```

**Comment by farahrobleh** [comment]
## 2024-10-23 Meeting Agenda

### Prework to prep for meeting
- [ ] Refer to live milestone issue
- [ ] Refer to HfLA PM Community of Practice Milestone Link for details: [Link here](https://github.com/hackforla/product-management/wiki/Milestones)
- [ ] Refer to Food Oasis Roadmap/Milestone/Spreadsheets 
- [ ] Review Food Oasis Marketing Epic https://github.com/hackforla/marketing/issues/74

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Website+and+Marketing+Content%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - Roll Call
    - [ ] Robleh
    - [ ] Bonnie
    - [ ] Sumit
    - [ ] Muthamil
    - [ ] Nate
- [ ]  Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Robleh](https://github.com/hackforla/food-oasis/issues/assigned/farahrobleh)
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)
       - [ ] [Sumit](https://github.com/hackforla/food-oasis/issues/assigned/sumit-sharma92)
       - [ ] [Muthamil](https://github.com/hackforla/food-oasis/issues/assigned/MuthamilselvanG)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Suggested next steps from [Self-service updates Google Doc](https://docs.google.com/document/d/1-kBfO2QmRa9ReeZQnK7E96_l_XRLOXWbm8wqxxFWIsw/edit?usp=sharing) have been enacted
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
- 

### Task Items
```

**Comment by farahrobleh** [comment]
## 2024-11-06 Meeting Agenda

### Prework to prep for meeting
- [ ] Refer to live milestone issue
- [ ] Refer to HfLA PM Community of Practice Milestone Link for details: [Link here](https://github.com/hackforla/product-management/wiki/Milestones)
- [ ] Refer to Food Oasis Roadmap/Milestone/Spreadsheets 

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Website+and+Marketing+Content%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - Roll Call
    - [ ] Robleh
    - [ ] Bonnie
    - [ ] Sumit
    - [ ] Muthamil
    - [ ] Nate
- [ ]  Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Robleh](https://github.com/hackforla/food-oasis/issues/assigned/farahrobleh)
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)
       - [ ] [Sumit](https://github.com/hackforla/food-oasis/issues/assigned/sumit-sharma92)
       - [ ] [Muthamil](https://github.com/hackforla/food-oasis/issues/assigned/MuthamilselvanG)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 

### FYIs
-

### Notes from Meeting
- 

### Task Items
```

**Comment by Rabia2219** [comment]
## 2025-04-16 Meeting Agenda

### Prework to prep for meeting
- [ ] add a link to the most recent label check to the agenda

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Product+Management%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/food-oasis/issues/2412

**Comment by TifNi** [comment]
2025-04-16
-Need Greg and Dr. Ban's availability for FOLA&GEOG 482/582
-Completed Weekly label check #1119 
-Recurring items will be introduced in the next meeting

**Comment by ExperimentsInHonesty** [comment]
## 2025-04-23 Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - [ ] review any issues that are in the [new issue approval column](https://github.com/orgs/hackforla/projects/59/views/3?filterQuery=label%3A%22Product+Management%22+-status%3AReference%2C%22In+Development%22++status%3A%22New+Issue+Approval%22)
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Jason](https://github.com/hackforla/food-oasis/issues/assigned/jaason-shi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by TifNi** [comment]
Notes from Meeting
- Completed https://github.com/hackforla/fola-geog-482-582/issues/20 and assigned to Project: https://github.com/orgs/hackforla/projects/140
- Added new label: Feature: "Feature: Board/Github Maintenance" 

Task Items
@jaason-shi - Assign Labels: Size, Role

**Comment by ExperimentsInHonesty** [comment]
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Nate
    - [ ] Natalie
    - [ ] Stella
    - [ ] Tiffany
    - [ ] Jason
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Jason](https://github.com/hackforla/food-oasis/issues/assigned/jaason-shi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by TifNi** [comment]
## [2025-05-07]  Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Nate
    - [ ] Natalie
    - [ ] Stella
    - [ ] Tiffany
    - [ ] Jason
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Jason](https://github.com/hackforla/food-oasis/issues/assigned/jaason-shi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Review (https://github.com/hackforla/food-oasis/issues/2419) to assign remaining Interface: Missing 
- [ ] Review (https://github.com/orgs/hackforla/projects/59/views/1?filterQuery=label%3A%22Interface%3A+missing%22+-status%3ADone) to assign remaining Interface: Missing from the Issue created by Stella
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by wmao8** [comment]
## 2025-05-13  Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Nate
    - [ ] Natalie
    - [ ] Stella
    - [ ] Tiffany
    - [ ] Jason
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Jason](https://github.com/hackforla/food-oasis/issues/assigned/jaason-shi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] TBU

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by TifNi** [comment]
## 2025-05-20 Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Nate
    - [ ] Natalie
    - [ ] Stella
    - [ ] Tiffany
    - [ ] Jason
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Jason](https://github.com/hackforla/food-oasis/issues/assigned/jaason-shi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by TifNi** [comment]
## 2025-06-04  Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Nate
    - [ ] Natalie
    - [ ] Stella
    - [ ] Tiffany
    - [ ] Jason
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Jason](https://github.com/hackforla/food-oasis/issues/assigned/jaason-shi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting
- Organize Prioritize Backlog

### Task Items

**Comment by pbandyop** [comment]
## 2025-08-13 Meeting Agenda

### Prework to prep for meeting
- [ ] 

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [x] Bonnie
    - [x] Payel
    - [ ] Nate
    - [ ] Natalie
    - [ ] Stella
    - [x] Tiffany
    - [ ] Jason
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Natalie](https://github.com/hackforla/food-oasis/issues/assigned/nataliecly)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Jason](https://github.com/hackforla/food-oasis/issues/assigned/jaason-shi)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Weekly label check https://github.com/hackforla/food-oasis/issues?q=is%3Aissue%20state%3Aopen%20-label%3A%22Role%3A%20DevOps%22%2C%22Role%3A%20Tester%22%2C%22Role%3A%20Back-end%22%2C%22Role%3A%20Database%22%2C%22Role%3A%20Front-end%22%2C%22Role%3A%20Full%20Stack%22%20-author%3Aentrotech%20-author%3Afancyham 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
- Before the next all team meeting
   - [ ] review the "ready for" labels and add any reminders needed to the column.
   - [ ] review last two weeks of all team meeting agendas for issues/discussions that did not get resolved.

**Comment by TifNi** [comment]
## 2025-08-26  Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Tiffany
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Nate](https://github.com/hackforla/food-oasis/issues/assigned/neom500)
       - [ ] [Stella](https://github.com/hackforla/food-oasis/issues/assigned/wmao8)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Chanel](https://github.com/hackforla/food-oasis/issues/assigned/ChanelYJ)
       - [ ] [JiaHui](https://github.com/hackforla/food-oasis/issues/assigned/annie1225jh)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by TifNi** [comment]
## 2025-11-04  Meeting Agenda

### Prework to prep for meeting
- [ ] do the #1119
- [ ] add a link to the most recent comment in the https://github.com/hackforla/food-oasis/issues/1119 to the agenda

### Recurring items: Happens on the Wednesday meeting
 - Roll Call
    - [ ] Bonnie
    - [ ] Payel
    - [ ] Tiffany
    - [ ] Alexa
    - [ ] Saumil

- [ ]  Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Bonnie](https://github.com/hackforla/food-oasis/issues/assigned/experimentsinhonesty)    
       - [ ] [Payel](https://github.com/hackforla/food-oasis/issues/assigned/pbandyop)
       - [ ] [Tiffany](https://github.com/hackforla/food-oasis/issues/assigned/TifNi)
       - [ ] [Alexa](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue%20state%3Aopen%20assignee%3ARay65)
       - [ ] [Saumil](https://github.com/hackforla/food-oasis/issues?q=is%3Aissue%20state%3Aopen%20assignee%3ASAUMILDHANKAR)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further (if necessary)
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs

### Notes from Meeting
- [ ] Alexa's [issues](https://github.com/hackforla/food-oasis/issues/2227#issuecomment-3487459367)
- [ ] Discuss research capability

### Task Items
