### ISSUE TITLE
FOLA: Reboot Milestones

### ISSUE THREAD

**Issue by farahrobleh** [hackforla/food-oasis#2232]
### Overview

We need to create a roadmap that includes the milestone list to help with product prioritisation, project monitoring and for the team to know what each task builds up to.

### Action Items

- [ ] Create milestone list using Guides template and project one sheet as examples
- [ ]  Meet with Bonnie to create list
- [ ]  Add Milestones to Repo
- [ ]  Add Milestones to each issue

### Resources/Instructions

- Refer to [this link](https://github.com/hackforla/product-management/wiki/Milestones) in the HfLA PM Community of Practice, Product Management wiki for details regarding milestones.
- [Food Oasis milestones alphabetically.](https://github.com/hackforla/food-oasis/milestones?direction=asc&sort=title&state=open)

#### Examples
- [Guides Project Roadmap](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
- [OCS Project Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)
