### ISSUE TITLE
Create an Admin Dashboard for Site Admins to Manage Stakeholder Verification, etc.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#293]
### Overview
Create a dashboard screen for an Administrator to be able to search and filter stakeholders by various useful criteria to implement the processes described below

### Action Items
- [x] - John to take a rough cut at a screen that allows an admin to search and filter by criteria needed to accomplish these procedures.
- [ ] - Jenny, Tina to review UI/UX and provide input for a second-pass with better user experience.
- [ ] - Refine implementation, and split out separate issues for specialized use cases.

### Resources/Instructions
https://docs.google.com/document/d/1NaMPWsWJvcTivgS6M6fuJPjdusj8TGMSmw9Pqk3ATbs/edit

Here are the functional requirements  from that document (Comments in parentheses indicate how to do this in the "first-cut" implementation):

- [x] 1. See who, when, and which record is updated. (Select criteria of interest, sort results by updated date descending)
- [x] 2. Have the ability to assign a stakeholder to a volunteer for verification. (Select criteria to find assigned = false, approved = false, then drill into desired stakeholder, and use the Assign To drop-down on the verification tab to assign to a person.) 
- [x] 3. See the database by groups of 3 that can be assigned to a specific volunteer. (Same as #2 above,  though we could modify to do it in batches, rather than one at a time.)
- [x] 4. See the collection of records that a volunteer believes to be complete. (Select criteria to show records that are verified, but not approved)
- [x] 5. Have the ability to see which stakeholders are verified, but not approved or rejected, and to approve or reject them. {Select criteria to show records that are verified, but not approved or rejected)
- [x] 6. Send approved records to the database. (Go to Edit page for stakeholder, click on approve or reject checkbox on verification tab, and press Save button.)
- [x] 7. List of records that are pending approval (ready to be approved). (Same as #5 above)
- [x] 8. List of records that have been approved. {Select criteria to show approved = yes)
- [x] 9. Ability to give suggestions or notes to a volunteer to make a record “approvable”. (At present, reject as in #6 above, and put suggestion(s) in Verification Notes field).
- [x] 10. If a record hasn’t been touched in a week, needs to be reassigned. (Select Criteria assigned = yes, approved =  no, then sort updated column descending to see assigned record that haven't been touched receently.)
- [ ] 11. List of current volunteers who are participating this week. - verify or save button. (Don't currently have a good way to do this, though you can see the records that have been marked verified and sort by updated date descending. There is not a criterion for finding records by who updated them at this  time.)

**Comment by entrotech** [comment]
Here are links to videos demonstrating the Verfication Admin screen (and Verification Dashboard for Data Entry users:

[Admin - Assigning and Reassigning Data Entry Users](https://www.loom.com/share/8d893033e6b94468aff7c2b6f54b3210)

[Data Entry User - Saving and Verifying](https://www.loom.com/share/85a0a0012eca4bf0b4aa406285f6a558)

[Admin - Reviewing Verified Organizations](https://www.loom.com/share/6a8854d2c82c40bea339d34a8fa207ba)

**Comment by entrotech** [comment]
Suggested improvement to functionality:

- Add a checkbox to the beginning of each row, allowing the admin to select mulitple rows, them have a button to assign and un-assign the selected stakeholders all at once. Similar to gmail bulk operations, and there might be other operations than assigning that this makes sense for.
- From Organization Edit page, Save button should go back to the Verification Admin screen or Verification Dashboard (depending on where the user came from - equivalent to using the browser's Back button.
- Bug: The assigned date is displayed in GMT (7 hours after local time) - need to fix.
- Bug: The inactive criteria is not working.
