### ISSUE TITLE
Improve Design of Organization Edit Form

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#320]
### Dependencies
#1142
#1141 
#1143
#1148

### Overview
The current implementation of the Organization edit form, shown in the screenshot below, was "designed" in an ad hoc fashion based on known requirements. It should have a proper design review and makeover by folks with a better design sense.

Consider whether a tabbed UI is appropriate, how buttons are labeled, the grouping of data onto tabs, the ordering of fields, the types of controls for each field, and, of course, the colors and layout.  Related to  Issues #315 and #316 about specific control situations.

### Action Items

Research
- [ ] Design Card Sorting exercise for Data Entry Volunteers #1143

Design
- [ ] Redesign tooltips #1148
- [ ] Create mockups for the new Organization Edit Form #1141

Engineering

- [ ] TBC

Product Management
- [ ] Create a wiki of the "Organization Form Fields" #1142

### Resources/Instructions
![image](https://user-images.githubusercontent.com/9939032/80407956-4ea4ce80-887b-11ea-9e4d-2626479dc06b.png)

**Comment by entrotech** [comment]
As of 3/23/21 this issue is somewhat stalled. The best wireframe we have for a proposed change can be found in the "\[Dashboard Redesign](https://www.figma.com/file/KZbof1x83FOvw4Jfc99EIf/Food-Oasis-Dashboards?node-id=521%3A67) figma file on the page called Draft 3- Jordan. This was orginally done by Jordan Romanoff, based on direction from Jenny and perhaps some other people. The left-hand man menu shown is not really part of the Organization Edit page, and the wrieframe dooesn't show any CTA buttons at all, so I'm not sure it the intent is to change the CTAs or not. Jenny's plan was to finalize this design with UX/UI people and then proceed to do UX testing with experienced volunteer users based on some sort of clickable prototype, before finalizing and specifying and issue for development.

**Comment by gigicobos** [comment]
**Meeting 01/06/2021**

We had a call to review all the issues from the [Heauristic Evaluation to Features](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=983594560) document and discuss the next steps to redesign the Organization Edit Form.

I've added details of the next steps on this issue and created issues #1142, #1141, #1143.

**Comment by staceyrebekahscott** [comment]
Automation moved this to Done when Seiko closed it, but she reopened it and it remained in the Done column. Moved back to Prioritized backlog for reassessment along with dependent issues.
