### ISSUE TITLE
Contact Connector - Hunger Relief Orgs

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/food-oasis#48]
### Tasks
- [ ] Find relevant organizations
- [ ] Use [research guide](https://docs.google.com/document/d/1l6KIEb1x7e_3lZdeFKEKsAvcNaD-RlxEHyRruLGdFI4/edit?usp=sharing) to conduct interview
- [ ] Save all data to [research folder](https://drive.google.com/drive/folders/12r33G1Ui2hpINLVfngR911B20ZclKKo3?usp=sharing)
- [ ] Add organization information to [stakeholder database](https://drive.google.com/drive/folders/1jfMFrMYPeAJHJu2OZ2rUpftJoRW2dEgh?usp=sharing)

### Resources
- Primary research guide: https://docs.google.com/document/d/1l6KIEb1x7e_3lZdeFKEKsAvcNaD-RlxEHyRruLGdFI4/edit?usp=sharing

- Research folder: https://drive.google.com/drive/folders/12r33G1Ui2hpINLVfngR911B20ZclKKo3?usp=sharing

- Stakeholder database: https://drive.google.com/drive/folders/1jfMFrMYPeAJHJu2OZ2rUpftJoRW2dEgh?usp=sharing
