### ISSUE TITLE
Update existing Food Seeker UI to reflect new design elements

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#507]
### Overview
Update existing Food Seeker UI (homepage, map page & organization detail) to reflect new design elements per the Style Guide for both desktop & mobile

### Action Items - Desktop
- [x] Redesign FOLA homepage with new Style Guide design elements (note: we will be sticking to the hamburger menu for MVP and pushing the ribbon menu to V2 due to dev complexity)
- [x] Redesign map page with new Style Guide design elements (#423) in Style Guide file
- [x] Use final copy from #480 

### Action Items - Mobile
- [x] Redesign FOLA homepage with new Style Guide design elements
- [x] Redesign map page with new Style Guide design elements (#423) in Style Guide file

### Resources/Instructions
- [Figma Food Seeker interface, desktop](https://www.figma.com/file/QgM5vS8NhDNXhknnFpu2Hn/Prototyping-in-Figma?node-id=26%3A394)
- [Figma Food Seeker interface, mobile](https://www.figma.com/file/Qs2zKdqZFLyPxc5qaaFCBk/FOLA-v4?node-id=0%3A1)

**Comment by lizagarrison** [comment]
[Design Guide / Sandbox](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=0%3A1)
