### ISSUE TITLE
Figure out Roadmap

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#873]
### Dependency 
Define advisory board #937

### Overview
We need to develop a roadmap so that we know what to work on next.  

### Action Items

- [x] Review Document
- [x] Discuss Document
- [ ] Start new Roadmap document

### Resources/Instructions
[John's document](https://docs.google.com/document/d/13bGxO5My3UjRk4cyEZR9DqyJ4VH2C63z34UUa5MFnlg/edit
)
[Working roadmap document](https://docs.google.com/document/d/1TFYAT3WD2GAtus7esh5Q33hfTkTBrjKRI7QyHGUllKs/edit#)

**Comment by ktjnyc** [comment]
Moving this to icebox while we put together the advisory board - #937

**Comment by wanderingspoon** [comment]
Files for roadmapping work sessions:

[DOC: Agendas](https://docs.google.com/document/d/1rRVCG8oZzle4MiZj3SR4nPO8KBxLaXS6WIbonU3xxOo/edit)

[DOC: Working document](https://docs.google.com/document/d/1TFYAT3WD2GAtus7esh5Q33hfTkTBrjKRI7QyHGUllKs/edit#heading=h.pg60j03tjzbq)

[SLIDES: Consensus Workshop](https://docs.google.com/presentation/d/1ts-04QVzXMd5e1c7bChZwwcZ6-AwMUWkbQsG-L_Z3GQ/edit#slide=id.gd9ac142bbe_0_209)

[FORM: Prioritization Survey](https://docs.google.com/forms/d/1FATPWYZTHmnyjvGVbHRD2IKorlOT0wVzS70DhQOC7z8/edit)

[SHEETS: Action Planning](https://docs.google.com/spreadsheets/d/1WrpaRQ3mBEfT3juBfQHFdCJ4Xbn2r-9oNp5oa6_NQO4/edit#gid=1121766691)

**Comment by wanderingspoon** [comment]
- [ ] Define success & deliverables
- [ ] Outline resource requirements
- [ ] Form teams
- [ ] Forecast project schedule

**Comment by fancyham** [comment]
From our workshops:

"Vision
We help people who are in need find free food.

We aim to become the easiest, most reliable, and most up-to-date way to connect food insecure people to food pantries and meal programs near them.


Goals
- Meet user needs, increase # users, help as many as we can (public site)
- Facilitate list updates, self-updating listings
- Sustain FOLA, generate revenue, sustainable opeations"

**Comment by fancyham** [comment]
Next step: the technical side of the road mapping.

Here’s a page listing out various “product prioritization frameworks”.  We’ll be using “Value vs Effort” to create our roadmap
https://roadmunk.com/guides/product-prioritization-techniques-product-managers/#2valuevseffort 

The entire team put together a list of possible projects for data validation.  Will be doing Public-facing site and FOLA sustainability next.

Putting this in here from a slack discussion so we don’t lose it — possibly for future road mapping exercises:

Our goal today is to come up with a list of possible projects, and hopefully rank them by how well we think they’ll help us accomplish the goals that we recently came to consensus on.

If possible, please think about the top 5–10 most important projects for your part of the app and be ready to enter them.

Review your notes/github/previous workshop and bring a list of possible projects that:

- (for the public-site) Meet user needs, increase # users, help as many food-seekers as we can
- Facilitate list updates, self-updating listings
- FOLA sustainability: generate revenue, sustainable operations
We will de-duplicate these lists and rank them as a group.

This list will go to the leads (PM, Engineering, Design) who will review and come up with estimates for effort and resources-needed.  From that, I think we’ll have a good handle of what projects we can accomplish now, as well as knowing which projects we need to recruit for.  Basically, a road map.

**Not sure what’s a project and what’s not?**

**What’s a project? (AKA ‘objectives’)**
Narrow in scope
Specific actions
Target for a team’s execution
Specific outcomes with concrete deliverables
Measurable success
Shorter term, time-bound
The means to the end result/goal

**Examples of projects:**
“Change multi-color icons on map to match order of panty / meal buttons”
“Add more filters to directory/map”
“Implement volunteer hour tracking”
“Evaluate volunteer data validation process”

**These are not projects:**
(because they’re too big — they’re goals and need to be broken up into projects)
“Improve NPS”
“Help as many food seekers as we can”


This is how to think about vision, goals, objectives/projects:

VISION (the change you want to see)
- Goal
  - Objective / project
  - Objective / project
    - Sub-objective / sub-project
    - Sub-objective / sub-project
- Goal
  - Objective / project
  - Objective / project
  - Objective / project

A WELL-STOCKED KITCHEN (Vision)
- Find food (goal)
  - Search website and get locations (objective/project)
  - Sign up at location
  - Get SNAP
    - Sign up for SNAP
    - Get approved for SNAP
- Get food
  - Drive to pantry
  - Grocery shop with CalFresh (SNAP) card


You can find projects and goals in our previous work:
This page from the consensus workshop (which of these can be projects?)
Concentrate especially on your part of the site (Andrew, Erika)
 https://docs.google.com/presentation/d/1Z-MbJZwsNzQFOgbt9mxOY4MLySYDdJXEUKy85fYNzQc/edit#slide=id.gd9ac142bbe_0_209

Also review github issues!

— Workshop happened —

Good job, us!

For everyone’s reference, here’s the resulting post-it document for today’s ‘possible projects for data validation’ exercise: 
[Possible projects post-it exercise]
(https://docs.google.com/presentation/d/1WFaUBse9cfOtjJPJBJVSVzrYv6g2hbyi-krTuVOO8Ok/edit#slide=id.gdde3009fa1_0_212)

Here’s the spreadsheet the team leads will be using to create effort and resources-needed estimates:
[Project prioritization worksheet:](https://docs.google.com/spreadsheets/d/1bkztIQr6IaEZA1QBZqIp5r-FnhWNvOceTHRYRrzRu3M/edit#gid=0)
