### ISSUE TITLE
Jenny Transition

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#886]
### Overview
We need a list of items to transition so Jenny can step away. 

### Action Items

- [x] Update contact email onFoodoasis.la pages to point to project email #891 
- [x] Confirm process for Jenny sign-off on volunteer hours 
- [ ] Confirm website domain ownership 
     - [x] Bonnie reaching out
- [x] Document listing approval process Issue #922 to track future work for this going forward.
- [x] Confirm [google drive clean up](https://docs.google.com/spreadsheets/d/1sUro4-Tx97N6tN_eAZpfVnqVmuCN3mYfH9Lq-rke0fQ/edit?usp=sharing) Issue #938 to track future work for this going forward.
- [x] Follow up Robin/Jordan regarding UI/UX changes to volunteer pages - Issue #968 to track future work for this going forward.
     - [x] Locate Figma 
     - [x] Get contact info for the testers that agreed to help
     - [x] Identify researchers to complete user testing 
     - [x] Connect with Jordan/Robin regarding process
- [x] Reach out to LA Works regarding volunteer training
     - [x] Reached out to Jordan via LA Works contact form
     - [x] Reached out to Jordan via email 
     - [x] Notes from meeting in #901 
- [x] Get list of outreach to other organizations
     - [Outreach spreadsheet](https://docs.google.com/spreadsheets/d/1rQSs3FJUn03rr1EEJKO9Fg9OWyzy4zlIt9vwWyIpP8A/edit?usp=sharing)
- [x] Review transition documentation
- [x] Get admin access to the FB and Instagram accounts 
- [x] Identify the purpose of FOLA - Outreach and Food Cycle 
- [x] Ecosystem mapping interview

   
### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by ktjnyc** [comment]
Sent email to Jordan Smith asking for time to discuss volunteer training.

**Comment by ktjnyc** [comment]
Issue #968 to track future work for the volunteer dashboard re-design going forward.
